typedef int bool;
typedef unsigned int size_t;
typedef unsigned short int uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long int uint64_t;
typedef unsigned short int uint16;
typedef unsigned int uint32;
typedef unsigned long int uint64;
void * __builtin_apply_args ();
void * __builtin_apply (void (*function)(), void *arguments, size_t size);
void __builtin_return (void *result);
void __builtin_va_arg_pack ();
size_t __builtin_va_arg_pack_len ();
void * __builtin_return_address (unsigned int level);
void * __builtin_extract_return_addr (void *addr);
void * __builtin_frob_return_address (void *addr);
void * __builtin_frame_address (unsigned int level);
bool __atomic_test_and_set (void *ptr, int memorder);
void __atomic_clear (bool *ptr, int memorder);
void __atomic_thread_fence (int memorder);
void __atomic_signal_fence (int memorder);
bool __atomic_always_lock_free (size_t size, void *ptr);
bool __atomic_is_lock_free (size_t size, void *ptr);
bool __builtin_sadd_overflow (int a, int b, int *res);
bool __builtin_saddl_overflow (long int a, long int b, long int *res);
bool __builtin_saddll_overflow (long long int a, long long int b, long int *res);
bool __builtin_uadd_overflow (unsigned int a, unsigned int b, unsigned int *res);
bool __builtin_uaddll_overflow (unsigned long long int a);
bool __builtin_ssub_overflow (int a, int b, int *res);
bool __builtin_ssubl_overflow (long int a, long int b, long int *res);
bool __builtin_ssubll_overflow (long long int a, long long int b, long int *res);
bool __builtin_usub_overflow (unsigned int a, unsigned int b, unsigned int *res);
bool __builtin_usubll_overflow (unsigned long long int a);
bool __builtin_smul_overflow (int a, int b, int *res);
bool __builtin_smull_overflow (long int a, long int b, long int *res);
bool __builtin_smulll_overflow (long long int a, long long);
bool __builtin_umul_overflow (unsigned int a, unsigned int b, unsigned int *res);
bool __builtin_umulll_overflow (unsigned long long int a);
void * __builtin___bnd_set_ptr_bounds (const void *q, size_t size);
void * __builtin___bnd_narrow_ptr_bounds (const void *p, const void *q, size_t size);
void * __builtin___bnd_copy_ptr_bounds (const void *q, const void *r);
void * __builtin___bnd_init_ptr_bounds (const void *q);
void * __builtin___bnd_null_ptr_bounds (const void *q);
void __builtin___bnd_store_ptr_bounds (const void **ptr_addr, const void *ptr_val);
void __builtin___bnd_chk_ptr_lbounds (const void *q);
void __builtin___bnd_chk_ptr_ubounds (const void *q);
void __builtin___bnd_chk_ptr_bounds (const void *q, size_t size);
const void * __builtin___bnd_get_ptr_lbound (const void *q);
const void * __builtin___bnd_get_ptr_ubound (const void *q);
void *__builtin_alloca (size_t size);
void *__builtin_alloca_with_align (size_t size, size_t pointer_exp);
int __builtin_constant_p (int exp);
long __builtin_expect (long exp, long c);
void __builtin_trap (void);
void __builtin_unreachable (void);
void * __builtin_assume_aligned (const void *exp, size_t align, ...);
int __builtin_LINE ();
const char * __builtin_FUNCTION ();
const char * __builtin_FILE ();
void __builtin___clear_cache (char *begin, char *end);
void __builtin_prefetch (const void *addr, ...);
double __builtin_huge_val (void);
float __builtin_huge_valf (void);
long double __builtin_huge_vall (void);
int __builtin_fpclassify (int, int, int, int, int, ...);
double __builtin_inf (void);
float __builtin_inff (void);
long double __builtin_infl (void);
double __builtin_nan (const char *str);
float __builtin_nanf (const char *str);
long double __builtin_nanl (const char *str);
double __builtin_nans (const char *str);
float __builtin_nansf (const char *str);
long double __builtin_nansl (const char *str);
int __builtin_ffs (int x);
int __builtin_clz (unsigned int x);
int __builtin_ctz (unsigned int x);
int __builtin_clrsb (int x);
int __builtin_popcount (unsigned int x);
int __builtin_parity (unsigned int x);
int __builtin_ffsl (long);
int __builtin_clzl (unsigned long);
int __builtin_ctzl (unsigned long);
int __builtin_clrsbl (long);
int __builtin_popcountl (unsigned long);
int __builtin_parityl (unsigned long);
int __builtin_ffsll (long long);
int __builtin_clzll (unsigned long long);
int __builtin_ctzll (unsigned long long);
int __builtin_clrsbll (long long);
int __builtin_popcountll (unsigned long long);
int __builtin_parityll (unsigned long long);
double __builtin_powi (double, int);
float __builtin_powif (float, int);
long double __builtin_powil (long double, int);
uint16_t __builtin_bswap16 (uint16_t x);
uint32_t __builtin_bswap32 (uint32_t x);
uint64_t __builtin_bswap64 (uint64_t x);
int __builtin_arc_aligned (void *val, int alignval);
void __builtin_arc_brk (void);
unsigned int __builtin_arc_core_read (unsigned int regno);
void __builtin_arc_core_write (unsigned int regno, unsigned int val);
int __builtin_arc_divaw (int a, int b);
void __builtin_arc_flag (unsigned int a);
unsigned int __builtin_arc_lr (unsigned int auxr);
void __builtin_arc_mul64 (int a, int b);
void __builtin_arc_mulu64 (unsigned int a, unsigned int b);
void __builtin_arc_nop (void);
int __builtin_arc_norm (int src);
short int __builtin_arc_normw (short int src);
void __builtin_arc_rtie (void);
void __builtin_arc_sr (unsigned int auxr, unsigned int val);
int __builtin_arc_swap (int src);
void __builtin_arc_swi (void);
void __builtin_arc_sync (void);
void __builtin_arc_trap_s (unsigned int c);
void __builtin_arc_unimp_s (void);
void __builtin_nds32_isync (int *addr);
void __builtin_nds32_isb (void);
int __builtin_nds32_mfsr (int sr);
int __builtin_nds32_mfusr (int usr);
void __builtin_nds32_mtsr (int value, int sr);
void __builtin_nds32_mtusr (int value, int usr);
void __builtin_nds32_setgie_en (void);
void __builtin_nds32_setgie_dis (void);
void __builtin_cpu_init (void);
int __builtin_cpu_is (const char *cpuname);
int __builtin_cpu_supports (const char *feature);
void __builtin_rx_brk (void);
void __builtin_rx_clrpsw (int);
void __builtin_rx_int (int);
void __builtin_rx_machi (int, int);
void __builtin_rx_maclo (int, int);
void __builtin_rx_mulhi (int, int);
void __builtin_rx_mullo (int, int);
int __builtin_rx_mvfachi (void);
int __builtin_rx_mvfacmi (void);
int __builtin_rx_mvfc (int);
void __builtin_rx_mvtachi (int);
void __builtin_rx_mvtaclo (int);
void __builtin_rx_mvtc (int reg, int val);
void __builtin_rx_mvtipl (int);
void __builtin_rx_racw (int);
int __builtin_rx_revw (int);
void __builtin_rx_rmpa (void);
void __builtin_rx_round (float);
int __builtin_rx_sat (int);
void __builtin_rx_setpsw (int);
void __builtin_rx_wait (void);
int __builtin_tbegin (void*);
int __builtin_tbegin_nofloat (void*);
int __builtin_tbegin_retry (void*, int);
int __builtin_tbegin_retry_nofloat (void*, int);
void __builtin_tbeginc (void);
int __builtin_tend (void);
void __builtin_tabort (int);
void __builtin_tx_assist (int);
int __builtin_tx_nesting_depth (void);
void __builtin_non_tx_store (uint64_t *, uint64_t);
void __builtin_set_thread_pointer (void *ptr);
void * __builtin_thread_pointer (void);
unsigned int __builtin_sh_get_fpscr (void);
void __builtin_sh_set_fpscr (unsigned int val);
void __builtin_cpu_init (void);
int __builtin_cpu_is (const char *cpuname);
int __builtin_cpu_supports (const char *feature);
size_t __builtin_object_size (void * ptr, int type);
void * __builtin___memcpy_chk (void *dest, const void *src, size_t n, size_t os);
void * __builtin___mempcpy_chk (void *dest, const void *src, size_t n, size_t os);
void * __builtin___memmove_chk (void *dest, const void *src, size_t n, size_t os);
void * __builtin___memset_chk (void *s, int c, size_t n, size_t os);
char * __builtin___strcpy_chk (char *dest, const char *src, size_t os);
char * __builtin___strncpy_chk (char *dest, const char *src, size_t n, size_t os);
char * __builtin___stpcpy_chk (char *dest, const char *src, size_t os);
char * __builtin___strcat_chk (char *dest, const char *src, size_t os);
char * __builtin___strncat_chk (char *dest, const char *src, size_t n, size_t os);
