typedef unsigned int size_t;
void * __builtin_apply_args ();
void * __builtin_apply (void (*function)(), void);
void __builtin_return (void *result);
__builtin_va_arg_pack ();
size_t __builtin_va_arg_pack_len ()
if (__builtin_va_arg_pack_len () > 1)
if (__builtin_constant_p (oflag))
if ((oflag & O_CREAT) != 0 && __builtin_va_arg_pack_len () < 1)
return open (path, oflag, __builtin_va_arg_pack ());
if (__builtin_va_arg_pack_len () < 1)
return open (path, oflag, __builtin_va_arg_pack ());
within individual functions. Mixed MIPS16 and non-MIPS16 code may interact badly with some GCC extensions such as __builtin_apply (see Section 6.5
void * __builtin_return_address (unsigned int level)
void * __builtin_extract_return_addr (void *addr)
void * __builtin_frob_return_address (void *addr)
void * __builtin_frame_address (unsigned int level)
Vector shuffling is available using functions __builtin_shuffle (vec, mask) and __
res = __builtin_shuffle (a, mask1);
res = __builtin_shuffle (a, b, mask2);
__builtin_offsetof (type, member)
bool __builtin_add_overflow (type1 a, type2 b, type3
bool __builtin_sadd_overflow (int a, int b, int *res)
bool __builtin_saddl_overflow (long int a, long int b, long
bool __builtin_saddll_overflow (long long int a, long long
bool __builtin_uadd_overflow (unsigned int a, unsigned int
bool __builtin_uaddl_overflow (unsigned long int a,
bool __builtin_uaddll_overflow (unsigned long long int a,
bool __builtin_sub_overflow (type1 a, type2 b, type3
bool __builtin_ssub_overflow (int a, int b, int *res)
bool __builtin_ssubl_overflow (long int a, long int b, long
bool __builtin_ssubll_overflow (long long int a, long long
bool __builtin_usub_overflow (unsigned int a, unsigned int
bool __builtin_usubl_overflow (unsigned long int a,
bool __builtin_usubll_overflow (unsigned long long int a,
bool __builtin_mul_overflow (type1 a, type2 b, type3
bool __builtin_smul_overflow (int a, int b, int *res)
bool __builtin_smull_overflow (long int a, long int b, long
bool __builtin_smulll_overflow (long long int a, long long
bool __builtin_umul_overflow (unsigned int a, unsigned int
bool __builtin_umull_overflow (unsigned long int a,
bool __builtin_umulll_overflow (unsigned long long int a,
size_t __builtin_object_size (void * ptr, int type)
points to at compile time, __builtin_object_size should return (size_t) -1 for
assert (__builtin_object_size (p, 0) == sizeof (var) - 1);
assert (__builtin_object_size (p, 1) == sizeof (var.buf1) - 1);
assert (__builtin_object_size (q, 0)
assert (__builtin_object_size (q, 1) == sizeof (var.b));
#define bos0(dest) __builtin_object_size (dest, 0)
__builtin___memcpy_chk (dest, src, n, bos0 (dest))
int __builtin___sprintf_chk (char *s, int flag, size_t os, const char *fmt, ...);
int __builtin___snprintf_chk (char *s, size_t maxlen, int flag, size_t os,
int __builtin___vsprintf_chk (char *s, int flag, size_t os, const char *fmt,
int __builtin___vsnprintf_chk (char *s, size_t maxlen, int flag, size_t os,
void * __builtin___bnd_set_ptr_bounds (const void *q,
if (!p) return __builtin___bnd_null_ptr_bounds (p);
return __builtin___bnd_set_ptr_bounds (p, n);
void * __builtin___bnd_narrow_ptr_bounds (const void
init_object (__builtin___bnd_narrow_ptr_bounds (objs + i, objs,
void * __builtin___bnd_copy_ptr_bounds (const void *q,
int *field_ptr = __builtin___bnd_copy_ptr_bounds (&objptr->int_field,
void * __builtin___bnd_init_ptr_bounds (const void *q)
void * __builtin___bnd_null_ptr_bounds (const void *q)
void __builtin___bnd_store_ptr_bounds (const void
void __builtin___bnd_chk_ptr_lbounds (const void *q)
__builtin___bnd_chk_ptr_lbounds (dst);
__builtin___bnd_chk_ptr_ubounds ((char *)dst + len - 1);
void __builtin___bnd_chk_ptr_ubounds (const void *q)
void __builtin___bnd_chk_ptr_bounds (const void *q, size t
const void * __builtin___bnd_get_ptr_lbound (const
void *lb = __builtin___bnd_get_ptr_lbound (q);
void *ub = __builtin___bnd_get_ptr_ubound (q);
const void * __builtin___bnd_get_ptr_ubound (const
void *__builtin_alloca (size t size)
a [i] = __builtin_alloca (n);
void *__builtin_alloca_with_align (size t size, size t
p = __builtin_alloca_with_align (n, 64 /* bits */);
p = __builtin_alloc (n);
int __builtin_types_compatible_p (type1, type2)
if (__builtin_types_compatible_p (typeof (x), long double)) \
else if (__builtin_types_compatible_p (typeof (x), double)) \
else if (__builtin_types_compatible_p (typeof (x), float)) \
type __builtin_call_with_static_chain (call_exp,
type __builtin_choose_expr (const_exp, exp1, exp2)
__builtin_choose_expr (
__builtin_types_compatible_p (typeof (x), double),
__builtin_choose_expr (
__builtin_types_compatible_p (typeof (x), float),
type __builtin_complex (real, imag)
int __builtin_constant_p (exp)
(__builtin_constant_p (X) \
__builtin_constant_p (EXPRESSION) ? (EXPRESSION) : -1,
long __builtin_expect (long exp, long c)
if (__builtin_expect (x, 0))
if (__builtin_expect (ptr != NULL, 1))
void __builtin_trap (void)
void __builtin_unreachable (void)
__builtin_unreachable ();
__builtin_unreachable ();
void * __builtin_assume_aligned (const void *exp, size t
void *x = __builtin_assume_aligned (arg, 16);
void *x = __builtin_assume_aligned (arg, 32, 8);
int __builtin_LINE ()
const char * __builtin_FUNCTION ()
const char * __builtin_FILE ()
void __builtin___clear_cache (char *begin, char *end)
void __builtin_prefetch (const void *addr, ...)
__builtin_prefetch (&a[i+j], 1, 1);
__builtin_prefetch (&b[i+j], 0, 1);
double __builtin_huge_val (void)
float __builtin_huge_valf (void)
long double __builtin_huge_vall (void)
int __builtin_fpclassify (int, int, int, int, int, ...)
double __builtin_inf (void)
_Decimal32 __builtin_infd32 (void)
_Decimal64 __builtin_infd64 (void)
_Decimal128 __builtin_infd128 (void)
float __builtin_inff (void)
long double __builtin_infl (void)
int __builtin_isinf_sign (...)
double __builtin_nan (const char *str)
_Decimal32 __builtin_nand32 (const char *str)
_Decimal64 __builtin_nand64 (const char *str)
_Decimal128 __builtin_nand128 (const char *str)
float __builtin_nanf (const char *str)
long double __builtin_nanl (const char *str)
double __builtin_nans (const char *str)
float __builtin_nansf (const char *str)
long double __builtin_nansl (const char *str)
int __builtin_ffs (int x)
int __builtin_clz (unsigned int x)
int __builtin_ctz (unsigned int x)
int __builtin_clrsb (int x)
int __builtin_popcount (unsigned int x)
int __builtin_parity (unsigned int x)
int __builtin_ffsl (long)
int __builtin_clzl (unsigned long)
int __builtin_ctzl (unsigned long)
int __builtin_clrsbl (long)
int __builtin_popcountl (unsigned long)
int __builtin_parityl (unsigned long)
int __builtin_ffsll (long long)
int __builtin_clzll (unsigned long long)
int __builtin_ctzll (unsigned long long)
int __builtin_clrsbll (long long)
int __builtin_popcountll (unsigned long long)
int __builtin_parityll (unsigned long long)
double __builtin_powi (double, int)
float __builtin_powif (float, int)
long double __builtin_powil (long double, int)
uint16_t __builtin_bswap16 (uint16 t x)
uint32_t __builtin_bswap32 (uint32 t x)
uint64_t __builtin_bswap64 (uint64 t x)
unsigned int __builtin_aarch64_get_fpcr ()
void __builtin_aarch64_set_fpcr (unsigned int)
unsigned int __builtin_aarch64_get_fpsr ()
void __builtin_aarch64_set_fpsr (unsigned int)
__builtin_alpha_implver (void)
__builtin_alpha_rpcc (void)
__builtin_alpha_amask (long)
__builtin_alpha_cmpbge (long, long)
__builtin_alpha_extbl (long, long)
__builtin_alpha_extwl (long, long)
__builtin_alpha_extll (long, long)
__builtin_alpha_extql (long, long)
__builtin_alpha_extwh (long, long)
__builtin_alpha_extlh (long, long)
__builtin_alpha_extqh (long, long)
__builtin_alpha_insbl (long, long)
__builtin_alpha_inswl (long, long)
__builtin_alpha_insll (long, long)
__builtin_alpha_insql (long, long)
__builtin_alpha_inswh (long, long)
__builtin_alpha_inslh (long, long)
__builtin_alpha_insqh (long, long)
__builtin_alpha_mskbl (long, long)
__builtin_alpha_mskwl (long, long)
__builtin_alpha_mskll (long, long)
__builtin_alpha_mskql (long, long)
__builtin_alpha_mskwh (long, long)
__builtin_alpha_msklh (long, long)
__builtin_alpha_mskqh (long, long)
__builtin_alpha_umulh (long, long)
__builtin_alpha_zap (long, long)
__builtin_alpha_zapnot (long, long)
__builtin_alpha_pklb (long)
__builtin_alpha_pkwb (long)
__builtin_alpha_unpkbl (long)
__builtin_alpha_unpkbw (long)
__builtin_alpha_minub8 (long, long)
__builtin_alpha_minsb8 (long, long)
__builtin_alpha_minuw4 (long, long)
__builtin_alpha_minsw4 (long, long)
__builtin_alpha_maxub8 (long, long)
__builtin_alpha_maxsb8 (long, long)
__builtin_alpha_maxuw4 (long, long)
__builtin_alpha_maxsw4 (long, long)
__builtin_alpha_perr (long, long)
long __builtin_alpha_cttz (long)
long __builtin_alpha_ctlz (long)
long __builtin_alpha_ctpop (long)
void *__builtin_thread_pointer (void)
void __builtin_set_thread_pointer (void *)
int __builtin_ldbio (volatile const void *)
int __builtin_ldbuio (volatile const void *)
int __builtin_ldhio (volatile const void *)
int __builtin_ldhuio (volatile const void *)
int __builtin_ldwio (volatile const void *)
void __builtin_stbio (volatile void *, int)
void __builtin_sthio (volatile void *, int)
void __builtin_stwio (volatile void *, int)
void __builtin_sync (void)
int __builtin_rdctl (int)
int __builtin_rdprs (int, int)
void __builtin_wrctl (int, int)
void __builtin_flushd (volatile void *)
void __builtin_flushda (volatile void *)
int __builtin_wrpie (int);
void __builtin_eni (int);
int __builtin_ldex (volatile const void *)
int __builtin_stex (volatile void *, int)
int __builtin_ldsex (volatile const void *)
int __builtin_stsex (volatile void *, int)
void __builtin_custom_n (void)
void __builtin_custom_ni (int)
void __builtin_custom_nf (float)
void __builtin_custom_np (void *)
void __builtin_custom_nii (int, int)
void __builtin_custom_nif (int, float)
void __builtin_custom_nip (int, void *)
void __builtin_custom_nfi (float, int)
void __builtin_custom_nff (float, float)
void __builtin_custom_nfp (float, void *)
void __builtin_custom_npi (void *, int)
void __builtin_custom_npf (void *, float)
void __builtin_custom_npp (void *, void *)
int __builtin_custom_in (void)
int __builtin_custom_ini (int)
int __builtin_custom_inf (float)
int __builtin_custom_inp (void *)
int __builtin_custom_inii (int, int)
int __builtin_custom_inif (int, float)
int __builtin_custom_inip (int, void *)
int __builtin_custom_infi (float, int)
int __builtin_custom_inff (float, float)
int __builtin_custom_infp (float, void *)
int __builtin_custom_inpi (void *, int)
int __builtin_custom_inpf (void *, float)
int __builtin_custom_inpp (void *, void *)
float __builtin_custom_fn (void)
float __builtin_custom_fni (int)
float __builtin_custom_fnf (float)
float __builtin_custom_fnp (void *)
float __builtin_custom_fnii (int, int)
float __builtin_custom_fnif (int, float)
float __builtin_custom_fnip (int, void *)
float __builtin_custom_fnfi (float, int)
float __builtin_custom_fnff (float, float)
float __builtin_custom_fnfp (float, void *)
float __builtin_custom_fnpi (void *, int)
float __builtin_custom_fnpf (void *, float)
float __builtin_custom_fnpp (void *, void *)
void * __builtin_custom_pn (void)
void * __builtin_custom_pni (int)
void * __builtin_custom_pnf (float)
void * __builtin_custom_pnp (void *)
void * __builtin_custom_pnii (int, int)
void * __builtin_custom_pnif (int, float)
void * __builtin_custom_pnip (int, void *)
void * __builtin_custom_pnfi (float, int)
void * __builtin_custom_pnff (float, float)
void * __builtin_custom_pnfp (float, void *)
void * __builtin_custom_pnpi (void *, int)
void * __builtin_custom_pnpf (void *, float)
void * __builtin_custom_pnpp (void *, void *)
int __builtin_arc_aligned (void *val, int alignval)
void __builtin_arc_brk (void)
unsigned int __builtin_arc_core_read (unsigned int
void __builtin_arc_core_write (unsigned int regno,
int __builtin_arc_divaw (int a, int b)
void __builtin_arc_flag (unsigned int a)
unsigned int __builtin_arc_lr (unsigned int auxr)
void __builtin_arc_mul64 (int a, int b)
void __builtin_arc_mulu64 (unsigned int a, unsigned int b)
void __builtin_arc_nop (void)
int __builtin_arc_norm (int src)
short int __builtin_arc_normw (short int src)
void __builtin_arc_rtie (void)
void __builtin_arc_sleep (int a
void __builtin_arc_sr (unsigned int auxr, unsigned int val)
int __builtin_arc_swap (int src)
void __builtin_arc_swi (void)
void __builtin_arc_sync (void)
void __builtin_arc_trap_s (unsigned int c)
void __builtin_arc_unimp_s (void)
void __builtin_arc_vdirun (int, int)
void __builtin_arc_vdorun (int, int)
void __builtin_arc_vdiwr (const int, int)
void __builtin_arc_vdowr (const int, int)
__builtin_arc_vendrec (int)
__builtin_arc_vrec (int)
__builtin_arc_vrecrun (int)
__builtin_arc_vrun (int)
__builtin_arc_vld32 (__v8hi, const int, const int)
__builtin_arc_vld32wh (__v8hi, const int, const int)
__builtin_arc_vld32wl (__v8hi, const int, const int)
__builtin_arc_vld64 (__v8hi, const int, const int)
__v8hi __builtin_arc_vld128 (const int, const int)
__v8hi __builtin_arc_vld64w (const int, const int)
void __builtin_arc_vst128 (__v8hi, const int, const int)
void __builtin_arc_vst64 (__v8hi, const int, const int)
void __builtin_arc_vst16_n (__v8hi, const int, const int, const int)
void __builtin_arc_vst32_n (__v8hi, const int, const int, const int)
int __builtin_arm_getwcgr0 (void)
void __builtin_arm_setwcgr0 (int)
int __builtin_arm_getwcgr1 (void)
void __builtin_arm_setwcgr1 (int)
int __builtin_arm_getwcgr2 (void)
void __builtin_arm_setwcgr2 (int)
int __builtin_arm_getwcgr3 (void)
void __builtin_arm_setwcgr3 (int)
int __builtin_arm_textrmsb (v8qi, int)
int __builtin_arm_textrmsh (v4hi, int)
int __builtin_arm_textrmsw (v2si, int)
int __builtin_arm_textrmub (v8qi, int)
int __builtin_arm_textrmuh (v4hi, int)
int __builtin_arm_textrmuw (v2si, int)
v8qi __builtin_arm_tinsrb (v8qi, int, int)
v4hi __builtin_arm_tinsrh (v4hi, int, int)
v2si __builtin_arm_tinsrw (v2si, int, int)
long long __builtin_arm_tmia (long long, int, int)
long long __builtin_arm_tmiabb (long long, int, int)
long long __builtin_arm_tmiabt (long long, int, int)
long long __builtin_arm_tmiaph (long long, int, int)
long long __builtin_arm_tmiatb (long long, int, int)
long long __builtin_arm_tmiatt (long long, int, int)
int __builtin_arm_tmovmskb (v8qi)
int __builtin_arm_tmovmskh (v4hi)
int __builtin_arm_tmovmskw (v2si)
long long __builtin_arm_waccb (v8qi)
long long __builtin_arm_wacch (v4hi)
long long __builtin_arm_waccw (v2si)
v8qi __builtin_arm_waddb (v8qi, v8qi)
v8qi __builtin_arm_waddbss (v8qi, v8qi)
v8qi __builtin_arm_waddbus (v8qi, v8qi)
v4hi __builtin_arm_waddh (v4hi, v4hi)
v4hi __builtin_arm_waddhss (v4hi, v4hi)
v4hi __builtin_arm_waddhus (v4hi, v4hi)
v2si __builtin_arm_waddw (v2si, v2si)
v2si __builtin_arm_waddwss (v2si, v2si)
v2si __builtin_arm_waddwus (v2si, v2si)
v8qi __builtin_arm_walign (v8qi, v8qi, int)
long __builtin_arm_wandn (long long, long long)
__builtin_arm_wavg2b (v8qi, v8qi)
__builtin_arm_wavg2br (v8qi, v8qi)
__builtin_arm_wavg2h (v4hi, v4hi)
__builtin_arm_wavg2hr (v4hi, v4hi)
__builtin_arm_wcmpeqb (v8qi, v8qi)
__builtin_arm_wcmpeqh (v4hi, v4hi)
__builtin_arm_wcmpeqw (v2si, v2si)
__builtin_arm_wcmpgtsb (v8qi, v8qi)
__builtin_arm_wcmpgtsh (v4hi, v4hi)
__builtin_arm_wcmpgtsw (v2si, v2si)
__builtin_arm_wcmpgtub (v8qi, v8qi)
__builtin_arm_wcmpgtuh (v4hi, v4hi)
__builtin_arm_wcmpgtuw (v2si, v2si)
long __builtin_arm_wmacs (long long, v4hi, v4hi)
long __builtin_arm_wmacsz (v4hi, v4hi)
long __builtin_arm_wmacu (long long, v4hi, v4hi)
long __builtin_arm_wmacuz (v4hi, v4hi)
__builtin_arm_wmadds (v4hi, v4hi)
__builtin_arm_wmaddu (v4hi, v4hi)
__builtin_arm_wmaxsb (v8qi, v8qi)
__builtin_arm_wmaxsh (v4hi, v4hi)
__builtin_arm_wmaxsw (v2si, v2si)
__builtin_arm_wmaxub (v8qi, v8qi)
__builtin_arm_wmaxuh (v4hi, v4hi)
__builtin_arm_wmaxuw (v2si, v2si)
__builtin_arm_wminsb (v8qi, v8qi)
__builtin_arm_wminsh (v4hi, v4hi)
__builtin_arm_wminsw (v2si, v2si)
__builtin_arm_wminub (v8qi, v8qi)
__builtin_arm_wminuh (v4hi, v4hi)
__builtin_arm_wminuw (v2si, v2si)
__builtin_arm_wmulsm (v4hi, v4hi)
__builtin_arm_wmulul (v4hi, v4hi)
__builtin_arm_wmulum (v4hi, v4hi)
long __builtin_arm_wor (long long, long long)
__builtin_arm_wpackdss (long long, long long)
__builtin_arm_wpackdus (long long, long long)
__builtin_arm_wpackhss (v4hi, v4hi)
__builtin_arm_wpackhus (v4hi, v4hi)
__builtin_arm_wpackwss (v2si, v2si)
__builtin_arm_wpackwus (v2si, v2si)
long __builtin_arm_wrord (long long, long long)
long __builtin_arm_wrordi (long long, int)
__builtin_arm_wrorh (v4hi, long long)
__builtin_arm_wrorhi (v4hi, int)
__builtin_arm_wrorw (v2si, long long)
__builtin_arm_wrorwi (v2si, int)
__builtin_arm_wsadb (v2si, v8qi, v8qi)
__builtin_arm_wsadbz (v8qi, v8qi)
__builtin_arm_wsadh (v2si, v4hi, v4hi)
__builtin_arm_wsadhz (v4hi, v4hi)
__builtin_arm_wshufh (v4hi, int)
long __builtin_arm_wslld (long long, long long)
long __builtin_arm_wslldi (long long, int)
__builtin_arm_wsllh (v4hi, long long)
__builtin_arm_wsllhi (v4hi, int)
__builtin_arm_wsllw (v2si, long long)
__builtin_arm_wsllwi (v2si, int)
long __builtin_arm_wsrad (long long, long long)
long __builtin_arm_wsradi (long long, int)
__builtin_arm_wsrah (v4hi, long long)
__builtin_arm_wsrahi (v4hi, int)
__builtin_arm_wsraw (v2si, long long)
__builtin_arm_wsrawi (v2si, int)
long __builtin_arm_wsrld (long long, long long)
long __builtin_arm_wsrldi (long long, int)
__builtin_arm_wsrlh (v4hi, long long)
__builtin_arm_wsrlhi (v4hi, int)
__builtin_arm_wsrlw (v2si, long long)
__builtin_arm_wsrlwi (v2si, int)
__builtin_arm_wsubb (v8qi, v8qi)
__builtin_arm_wsubbss (v8qi, v8qi)
__builtin_arm_wsubbus (v8qi, v8qi)
__builtin_arm_wsubh (v4hi, v4hi)
__builtin_arm_wsubhss (v4hi, v4hi)
__builtin_arm_wsubhus (v4hi, v4hi)
__builtin_arm_wsubw (v2si, v2si)
__builtin_arm_wsubwss (v2si, v2si)
__builtin_arm_wsubwus (v2si, v2si)
__builtin_arm_wunpckehsb (v8qi)
__builtin_arm_wunpckehsh (v4hi)
long __builtin_arm_wunpckehsw (v2si)
__builtin_arm_wunpckehub (v8qi)
__builtin_arm_wunpckehuh (v4hi)
long __builtin_arm_wunpckehuw (v2si)
__builtin_arm_wunpckelsb (v8qi)
__builtin_arm_wunpckelsh (v4hi)
long __builtin_arm_wunpckelsw (v2si)
__builtin_arm_wunpckelub (v8qi)
__builtin_arm_wunpckeluh (v4hi)
long __builtin_arm_wunpckeluw (v2si)
__builtin_arm_wunpckihb (v8qi, v8qi)
__builtin_arm_wunpckihh (v4hi, v4hi)
__builtin_arm_wunpckihw (v2si, v2si)
__builtin_arm_wunpckilb (v8qi, v8qi)
__builtin_arm_wunpckilh (v4hi, v4hi)
__builtin_arm_wunpckilw (v2si, v2si)
long __builtin_arm_wxor (long long, long long)
long __builtin_arm_wzero ()
unsigned int __builtin_arm_get_fpscr ()
void __builtin_arm_set_fpscr (unsigned int)
void __builtin_avr_nop (void)
void __builtin_avr_sei (void)
void __builtin_avr_cli (void)
void __builtin_avr_sleep (void)
void __builtin_avr_wdr (void)
unsigned char __builtin_avr_swap (unsigned char)
unsigned int __builtin_avr_fmul (unsigned char, unsigned char)
int __builtin_avr_fmuls (char, char)
int __builtin_avr_fmulsu (char, unsigned char)
void __builtin_avr_delay_cycles (unsigned long ticks)
char __builtin_avr_flash_segment (const __memx void*)
unsigned char __builtin_avr_insert_bits (unsigned long map, unsigned char bits, unsigned char val)
__builtin_avr_insert_bits (0xffffffff, bits, val)
__builtin_avr_insert_bits (0x76543210, bits, val)
__builtin_avr_insert_bits (0x32107654, bits, 0)
__builtin_avr_insert_bits (0xffff3210, bits, val)
__builtin_avr_insert_bits (0x01234567, bits, 0)
void __builtin_bfin_csync (void)
void __builtin_bfin_ssync (void)
unsigned char __builtin_read8 (void *data)
unsigned short __builtin_read16 (void *data)
unsigned long __builtin_read32 (void *data)
unsigned long long __builtin_read64 (void *data)
void __builtin_write8 (void *data, unsigned char datum)
void __builtin_write16 (void *data, unsigned short datum)
void __builtin_write32 (void *data, unsigned long datum)
void __builtin_write64 (void *data, unsigned long long datum)
v2q15 __builtin_mips_addq_ph (v2q15, v2q15)
v2q15 __builtin_mips_addq_s_ph (v2q15, v2q15)
q31 __builtin_mips_addq_s_w (q31, q31)
v4i8 __builtin_mips_addu_qb (v4i8, v4i8)
v4i8 __builtin_mips_addu_s_qb (v4i8, v4i8)
v2q15 __builtin_mips_subq_ph (v2q15, v2q15)
v2q15 __builtin_mips_subq_s_ph (v2q15, v2q15)
q31 __builtin_mips_subq_s_w (q31, q31)
v4i8 __builtin_mips_subu_qb (v4i8, v4i8)
v4i8 __builtin_mips_subu_s_qb (v4i8, v4i8)
i32 __builtin_mips_addsc (i32, i32)
i32 __builtin_mips_addwc (i32, i32)
i32 __builtin_mips_modsub (i32, i32)
i32 __builtin_mips_raddu_w_qb (v4i8)
v2q15 __builtin_mips_absq_s_ph (v2q15)
q31 __builtin_mips_absq_s_w (q31)
v4i8 __builtin_mips_precrq_qb_ph (v2q15, v2q15)
v2q15 __builtin_mips_precrq_ph_w (q31, q31)
v2q15 __builtin_mips_precrq_rs_ph_w (q31, q31)
v4i8 __builtin_mips_precrqu_s_qb_ph (v2q15, v2q15)
q31 __builtin_mips_preceq_w_phl (v2q15)
q31 __builtin_mips_preceq_w_phr (v2q15)
v2q15 __builtin_mips_precequ_ph_qbl (v4i8)
v2q15 __builtin_mips_precequ_ph_qbr (v4i8)
v2q15 __builtin_mips_precequ_ph_qbla (v4i8)
v2q15 __builtin_mips_precequ_ph_qbra (v4i8)
v2q15 __builtin_mips_preceu_ph_qbl (v4i8)
v2q15 __builtin_mips_preceu_ph_qbr (v4i8)
v2q15 __builtin_mips_preceu_ph_qbla (v4i8)
v2q15 __builtin_mips_preceu_ph_qbra (v4i8)
v4i8 __builtin_mips_shll_qb (v4i8, imm0_7)
v4i8 __builtin_mips_shll_qb (v4i8, i32)
v2q15 __builtin_mips_shll_ph (v2q15, imm0_15)
v2q15 __builtin_mips_shll_ph (v2q15, i32)
v2q15 __builtin_mips_shll_s_ph (v2q15, imm0_15)
v2q15 __builtin_mips_shll_s_ph (v2q15, i32)
q31 __builtin_mips_shll_s_w (q31, imm0_31)
q31 __builtin_mips_shll_s_w (q31, i32)
v4i8 __builtin_mips_shrl_qb (v4i8, imm0_7)
v4i8 __builtin_mips_shrl_qb (v4i8, i32)
v2q15 __builtin_mips_shra_ph (v2q15, imm0_15)
v2q15 __builtin_mips_shra_ph (v2q15, i32)
v2q15 __builtin_mips_shra_r_ph (v2q15, imm0_15)
v2q15 __builtin_mips_shra_r_ph (v2q15, i32)
q31 __builtin_mips_shra_r_w (q31, imm0_31)
q31 __builtin_mips_shra_r_w (q31, i32)
v2q15 __builtin_mips_muleu_s_ph_qbl (v4i8, v2q15)
v2q15 __builtin_mips_muleu_s_ph_qbr (v4i8, v2q15)
v2q15 __builtin_mips_mulq_rs_ph (v2q15, v2q15)
q31 __builtin_mips_muleq_s_w_phl (v2q15, v2q15)
q31 __builtin_mips_muleq_s_w_phr (v2q15, v2q15)
a64 __builtin_mips_dpau_h_qbl (a64, v4i8, v4i8)
a64 __builtin_mips_dpau_h_qbr (a64, v4i8, v4i8)
a64 __builtin_mips_dpsu_h_qbl (a64, v4i8, v4i8)
a64 __builtin_mips_dpsu_h_qbr (a64, v4i8, v4i8)
a64 __builtin_mips_dpaq_s_w_ph (a64, v2q15, v2q15)
a64 __builtin_mips_dpaq_sa_l_w (a64, q31, q31)
a64 __builtin_mips_dpsq_s_w_ph (a64, v2q15, v2q15)
a64 __builtin_mips_dpsq_sa_l_w (a64, q31, q31)
a64 __builtin_mips_mulsaq_s_w_ph (a64, v2q15, v2q15)
a64 __builtin_mips_maq_s_w_phl (a64, v2q15, v2q15)
a64 __builtin_mips_maq_s_w_phr (a64, v2q15, v2q15)
a64 __builtin_mips_maq_sa_w_phl (a64, v2q15, v2q15)
a64 __builtin_mips_maq_sa_w_phr (a64, v2q15, v2q15)
i32 __builtin_mips_bitrev (i32)
i32 __builtin_mips_insv (i32, i32)
v4i8 __builtin_mips_repl_qb (imm0_255)
v4i8 __builtin_mips_repl_qb (i32)
v2q15 __builtin_mips_repl_ph (imm_n512_511)
v2q15 __builtin_mips_repl_ph (i32)
void __builtin_mips_cmpu_eq_qb (v4i8, v4i8)
void __builtin_mips_cmpu_lt_qb (v4i8, v4i8)
void __builtin_mips_cmpu_le_qb (v4i8, v4i8)
i32 __builtin_mips_cmpgu_eq_qb (v4i8, v4i8)
i32 __builtin_mips_cmpgu_lt_qb (v4i8, v4i8)
i32 __builtin_mips_cmpgu_le_qb (v4i8, v4i8)
void __builtin_mips_cmp_eq_ph (v2q15, v2q15)
void __builtin_mips_cmp_lt_ph (v2q15, v2q15)
void __builtin_mips_cmp_le_ph (v2q15, v2q15)
v4i8 __builtin_mips_pick_qb (v4i8, v4i8)
v2q15 __builtin_mips_pick_ph (v2q15, v2q15)
v2q15 __builtin_mips_packrl_ph (v2q15, v2q15)
i32 __builtin_mips_extr_w (a64, imm0_31)
i32 __builtin_mips_extr_w (a64, i32)
i32 __builtin_mips_extr_r_w (a64, imm0_31)
i32 __builtin_mips_extr_s_h (a64, i32)
i32 __builtin_mips_extr_rs_w (a64, imm0_31)
i32 __builtin_mips_extr_rs_w (a64, i32)
i32 __builtin_mips_extr_s_h (a64, imm0_31)
i32 __builtin_mips_extr_r_w (a64, i32)
i32 __builtin_mips_extp (a64, imm0_31)
i32 __builtin_mips_extp (a64, i32)
i32 __builtin_mips_extpdp (a64, imm0_31)
i32 __builtin_mips_extpdp (a64, i32)
a64 __builtin_mips_shilo (a64, imm_n32_31)
a64 __builtin_mips_shilo (a64, i32)
a64 __builtin_mips_mthlip (a64, i32)
void __builtin_mips_wrdsp (i32, imm0_63)
i32 __builtin_mips_rddsp (imm0_63)
i32 __builtin_mips_lbux (void *, i32)
i32 __builtin_mips_lhx (void *, i32)
i32 __builtin_mips_lwx (void *, i32)
a64 __builtin_mips_ldx (void *, i32) [MIPS64 only]
i32 __builtin_mips_bposge32 (void)
a64 __builtin_mips_madd (a64, i32, i32);
a64 __builtin_mips_maddu (a64, ui32, ui32);
a64 __builtin_mips_msub (a64, i32, i32);
a64 __builtin_mips_msubu (a64, ui32, ui32);
a64 __builtin_mips_mult (i32, i32);
a64 __builtin_mips_multu (ui32, ui32);
v4q7 __builtin_mips_absq_s_qb (v4q7);
v2i16 __builtin_mips_addu_ph (v2i16, v2i16);
v2i16 __builtin_mips_addu_s_ph (v2i16, v2i16);
v4i8 __builtin_mips_adduh_qb (v4i8, v4i8);
v4i8 __builtin_mips_adduh_r_qb (v4i8, v4i8);
i32 __builtin_mips_append (i32, i32, imm0_31);
i32 __builtin_mips_balign (i32, i32, imm0_3);
i32 __builtin_mips_cmpgdu_eq_qb (v4i8, v4i8);
i32 __builtin_mips_cmpgdu_lt_qb (v4i8, v4i8);
i32 __builtin_mips_cmpgdu_le_qb (v4i8, v4i8);
a64 __builtin_mips_dpa_w_ph (a64, v2i16, v2i16);
a64 __builtin_mips_dps_w_ph (a64, v2i16, v2i16);
v2i16 __builtin_mips_mul_ph (v2i16, v2i16);
v2i16 __builtin_mips_mul_s_ph (v2i16, v2i16);
q31 __builtin_mips_mulq_rs_w (q31, q31);
v2q15 __builtin_mips_mulq_s_ph (v2q15, v2q15);
q31 __builtin_mips_mulq_s_w (q31, q31);
a64 __builtin_mips_mulsa_w_ph (a64, v2i16, v2i16);
v4i8 __builtin_mips_precr_qb_ph (v2i16, v2i16);
v2i16 __builtin_mips_precr_sra_ph_w (i32, i32, imm0_31);
v2i16 __builtin_mips_precr_sra_r_ph_w (i32, i32, imm0_31);
i32 __builtin_mips_prepend (i32, i32, imm0_31);
v4i8 __builtin_mips_shra_qb (v4i8, imm0_7);
v4i8 __builtin_mips_shra_r_qb (v4i8, imm0_7);
v4i8 __builtin_mips_shra_qb (v4i8, i32);
v4i8 __builtin_mips_shra_r_qb (v4i8, i32);
v2i16 __builtin_mips_shrl_ph (v2i16, imm0_15);
v2i16 __builtin_mips_shrl_ph (v2i16, i32);
v2i16 __builtin_mips_subu_ph (v2i16, v2i16);
v2i16 __builtin_mips_subu_s_ph (v2i16, v2i16);
v4i8 __builtin_mips_subuh_qb (v4i8, v4i8);
v4i8 __builtin_mips_subuh_r_qb (v4i8, v4i8);
v2q15 __builtin_mips_addqh_ph (v2q15, v2q15);
v2q15 __builtin_mips_addqh_r_ph (v2q15, v2q15);
q31 __builtin_mips_addqh_w (q31, q31);
q31 __builtin_mips_addqh_r_w (q31, q31);
v2q15 __builtin_mips_subqh_ph (v2q15, v2q15);
v2q15 __builtin_mips_subqh_r_ph (v2q15, v2q15);
q31 __builtin_mips_subqh_w (q31, q31);
q31 __builtin_mips_subqh_r_w (q31, q31);
a64 __builtin_mips_dpax_w_ph (a64, v2i16, v2i16);
a64 __builtin_mips_dpsx_w_ph (a64, v2i16, v2i16);
a64 __builtin_mips_dpaqx_s_w_ph (a64, v2q15, v2q15);
a64 __builtin_mips_dpaqx_sa_w_ph (a64, v2q15, v2q15);
a64 __builtin_mips_dpsqx_s_w_ph (a64, v2q15, v2q15);
a64 __builtin_mips_dpsqx_sa_w_ph (a64, v2q15, v2q15);
v2sf __builtin_mips_pll_ps (v2sf, v2sf)
v2sf __builtin_mips_pul_ps (v2sf, v2sf)
v2sf __builtin_mips_plu_ps (v2sf, v2sf)
v2sf __builtin_mips_puu_ps (v2sf, v2sf)
v2sf __builtin_mips_cvt_ps_s (float, float)
float __builtin_mips_cvt_s_pl (v2sf)
float __builtin_mips_cvt_s_pu (v2sf)
v2sf __builtin_mips_abs_ps (v2sf)
v2sf __builtin_mips_alnv_ps (v2sf, v2sf, int)
v2sf __builtin_mips_movt_c_cond_ps (v2sf a, v2sf b, v2sf c, v2sf d)
v2sf __builtin_mips_movf_c_cond_ps (v2sf a, v2sf b, v2sf c, v2sf d)
int __builtin_mips_upper_c_cond_ps (v2sf a, v2sf b)
int __builtin_mips_lower_c_cond_ps (v2sf a, v2sf b)
if (__builtin_mips_upper_c_eq_ps (a, b))
if (__builtin_mips_lower_c_eq_ps (a, b))
v2sf __builtin_mips_addr_ps (v2sf, v2sf)
v2sf __builtin_mips_mulr_ps (v2sf, v2sf)
v2sf __builtin_mips_cvt_pw_ps (v2sf)
v2sf __builtin_mips_cvt_ps_pw (v2sf)
float __builtin_mips_recip1_s (float)
double __builtin_mips_recip1_d (double)
v2sf __builtin_mips_recip1_ps (v2sf)
float __builtin_mips_recip2_s (float, float)
double __builtin_mips_recip2_d (double, double)
v2sf __builtin_mips_recip2_ps (v2sf, v2sf)
float __builtin_mips_rsqrt1_s (float)
double __builtin_mips_rsqrt1_d (double)
v2sf __builtin_mips_rsqrt1_ps (v2sf)
float __builtin_mips_rsqrt2_s (float, float)
double __builtin_mips_rsqrt2_d (double, double)
v2sf __builtin_mips_rsqrt2_ps (v2sf, v2sf)
int __builtin_mips_cabs_cond_s (float a, float b)
int __builtin_mips_cabs_cond_d (double a, double b)
if (__builtin_mips_cabs_eq_s (a, b))
int __builtin_mips_upper_cabs_cond_ps (v2sf a, v2sf b)
int __builtin_mips_lower_cabs_cond_ps (v2sf a, v2sf b)
if (__builtin_mips_upper_cabs_eq_ps (a, b))
if (__builtin_mips_lower_cabs_eq_ps (a, b))
v2sf __builtin_mips_movt_cabs_cond_ps (v2sf a, v2sf b, v2sf c, v2sf d)
v2sf __builtin_mips_movf_cabs_cond_ps (v2sf a, v2sf b, v2sf c, v2sf d)
__builtin_mips_any_c_cond_ps (v2sf a, v2sf b)
__builtin_mips_all_c_cond_ps (v2sf a, v2sf b)
__builtin_mips_any_cabs_cond_ps (v2sf a, v2sf b)
__builtin_mips_all_cabs_cond_ps (v2sf a, v2sf b)
if (__builtin_mips_any_c_eq_ps (a, b))
if (__builtin_mips_all_c_eq_ps (a, b))
__builtin_mips_any_c_cond_4s (v2sf a, v2sf b, v2sf c, v2sf d)
__builtin_mips_all_c_cond_4s (v2sf a, v2sf b, v2sf c, v2sf d)
__builtin_mips_any_cabs_cond_4s (v2sf a, v2sf b, v2sf c, v2sf d)
__builtin_mips_all_cabs_cond_4s (v2sf a, v2sf b, v2sf c, v2sf d)
if (__builtin_mips_any_c_eq_4s (a, b, c, d))
if (__builtin_mips_all_c_eq_4s (a, b, c, d))
void __builtin_mips_cache (int op, const volatile void *addr)
unsigned int __builtin_mips_get_fcsr (void)
void __builtin_mips_set_fcsr (unsigned int value)
void __builtin_nds32_isync (int *addr)
void __builtin_nds32_isb (void)
int __builtin_nds32_mfsr (int sr)
int __builtin_nds32_mfusr (int usr)
void __builtin_nds32_mtsr (int value, int sr)
void __builtin_nds32_mtusr (int value, int usr)
void __builtin_nds32_setgie_en (void)
void __builtin_nds32_setgie_dis (void)
int __builtin_sbc (int value)
int __builtin_byteswap (int value)
int __builtin_brev (int value)
int __builtin_adds (int x, int y)
int __builtin_subs (int x, int y)
void __builtin_halt (void)
void __builtin_cpu_init (void)
int __builtin_cpu_is (const char *cpuname)
if (__builtin_cpu_is ("power8"))
int __builtin_cpu_supports (const char *feature)
if (__builtin_cpu_supports ("fpu"))
float __builtin_recipdivf (float, float);
float __builtin_rsqrtf (float);
double __builtin_recipdiv (double, double);
double __builtin_rsqrt (double);
uint64_t __builtin_ppc_get_timebase ();
unsigned long __builtin_ppc_mftb ();
double __builtin_unpack_longdouble (long double, int);
long double __builtin_pack_longdouble (double, double);
long __builtin_bpermd (long, long);
int __builtin_divwe (int, int);
int __builtin_divweo (int, int);
unsigned int __builtin_divweu (unsigned int, unsigned int);
unsigned int __builtin_divweuo (unsigned int, unsigned int);
long __builtin_divde (long, long);
long __builtin_divdeo (long, long);
unsigned long __builtin_divdeu (unsigned long, unsigned long);
unsigned long __builtin_divdeuo (unsigned long, unsigned long);
_Decimal64 __builtin_dxex (_Decimal64);
_Decimal128 __builtin_dxexq (_Decimal128);
_Decimal64 __builtin_ddedpd (int, _Decimal64);
_Decimal128 __builtin_ddedpdq (int, _Decimal128);
_Decimal64 __builtin_denbcd (int, _Decimal64);
_Decimal128 __builtin_denbcdq (int, _Decimal128);
_Decimal64 __builtin_diex (_Decimal64, _Decimal64);
_Decimal64 __builtin_dscli (_Decimal64, int);
_Decimal128 __builtin_dscliq (_Decimal128, int);
_Decimal64 __builtin_dscri (_Decimal64, int);
_Decimal128 __builtin_dscriq (_Decimal128, int);
unsigned long long __builtin_unpack_dec128 (_Decimal128, int);
_Decimal128 __builtin_pack_dec128 (unsigned long long, unsigned long long);
unsigned long long __builtin_unpack_vector_int128 (vector __int128_t, int);
vector __int128_t __builtin_pack_vector_int128 (unsigned long long,
vector __int128_t __builtin_bcdadd (vector __int128_t, vector__int128_t);
int __builtin_bcdadd_lt (vector __int128_t, vector__int128_t);
int __builtin_bcdadd_eq (vector __int128_t, vector__int128_t);
int __builtin_bcdadd_gt (vector __int128_t, vector__int128_t);
int __builtin_bcdadd_ov (vector __int128_t, vector__int128_t);
int __builtin_bcdsub_lt (vector __int128_t, vector__int128_t);
int __builtin_bcdsub_eq (vector __int128_t, vector__int128_t);
int __builtin_bcdsub_gt (vector __int128_t, vector__int128_t);
int __builtin_bcdsub_ov (vector __int128_t, vector__int128_t);
vector unsigned long long __builtin_crypto_vsbox (vector unsigned long long);
vector unsigned long long __builtin_crypto_vcipher (vector unsigned long long,
vector unsigned long long __builtin_crypto_vncipher (vector unsigned long long,
vector unsigned char __builtin_crypto_vpermxor (vector unsigned char,
vector unsigned short __builtin_crypto_vpermxor (vector unsigned short,
vector unsigned int __builtin_crypto_vpermxor (vector unsigned int,
vector unsigned long long __builtin_crypto_vpermxor (vector unsigned long long,
vector unsigned char __builtin_crypto_vpmsumb (vector unsigned char,
vector unsigned short __builtin_crypto_vpmsumb (vector unsigned short,
vector unsigned int __builtin_crypto_vpmsumb (vector unsigned int,
vector unsigned long long __builtin_crypto_vpmsumb (vector unsigned long long,
vector unsigned int __builtin_crypto_vshasigmaw (vector unsigned int,
unsigned int __builtin_tbegin (unsigned int)
unsigned int __builtin_tend (unsigned int)
__builtin_tabort (unsigned int)
__builtin_tabortdc (unsigned int, unsigned int, unsigned int)
__builtin_tabortdci (unsigned int, unsigned int, int)
__builtin_tabortwc (unsigned int, unsigned int, unsigned int)
__builtin_tabortwci (unsigned int, unsigned int, int)
__builtin_tcheck (void)
__builtin_treclaim (unsigned int)
__builtin_trechkpt (void)
__builtin_tsr (unsigned int)
unsigned int __builtin_tendall (void)
unsigned int __builtin_tresume (void)
unsigned int __builtin_tsuspend (void)
__builtin_get_texasr (void)
__builtin_get_texasru (void)
__builtin_get_tfhar (void)
__builtin_get_tfiar (void)
__builtin_set_texasr (unsigned long);
__builtin_set_texasru (unsigned long);
__builtin_set_tfhar (unsigned long);
__builtin_set_tfiar (unsigned long);
if (__builtin_tbegin (0))
__builtin_tabort (0);
__builtin_tend (0);
|| _TEXASRU_FAILURE_PERSISTENT (__builtin_get_texasru ()))
unsigned long __builtin_ttest (void)
unsigned char tx_state = _HTM_STATE (__builtin_ttest ());
void __builtin_rx_brk (void)
void __builtin_rx_clrpsw (int)
void __builtin_rx_int (int)
void __builtin_rx_machi (int, int)
void __builtin_rx_maclo (int, int)
void __builtin_rx_mulhi (int, int)
void __builtin_rx_mullo (int, int)
int __builtin_rx_mvfachi (void)
int __builtin_rx_mvfacmi (void)
int __builtin_rx_mvfc (int)
void __builtin_rx_mvtachi (int)
void __builtin_rx_mvtaclo (int)
void __builtin_rx_mvtc (int reg, int val)
void __builtin_rx_mvtipl (int)
void __builtin_rx_racw (int)
int __builtin_rx_revw (int)
void __builtin_rx_rmpa (void)
void __builtin_rx_round (float)
int __builtin_rx_sat (int)
void __builtin_rx_setpsw (int)
void __builtin_rx_wait (void)
int __builtin_tbegin (void*)
int __builtin_tbegin_nofloat (void*)
int __builtin_tbegin_retry (void*, int)
int __builtin_tbegin_retry_nofloat (void*, int)
void __builtin_tbeginc (void)
int __builtin_tend (void)
void __builtin_tabort (int)
void __builtin_tx_assist (int)
int __builtin_tx_nesting_depth (void)
void __builtin_non_tx_store (uint64 t *, uint64 t)
void __builtin_set_thread_pointer (void *ptr)
void * __builtin_thread_pointer (void)
return ((my_tcb*)__builtin_thread_pointer ())->c;
unsigned int __builtin_sh_get_fpscr (void)
void __builtin_sh_set_fpscr (unsigned int val)
void __builtin_vis_write_gsr (int64_t);
int64_t __builtin_vis_read_gsr (void);
void * __builtin_vis_alignaddr (void *, long);
void * __builtin_vis_alignaddrl (void *, long);
int64_t __builtin_vis_faligndatadi (int64_t, int64_t);
v2si __builtin_vis_faligndatav2si (v2si, v2si);
v4hi __builtin_vis_faligndatav4hi (v4si, v4si);
v8qi __builtin_vis_faligndatav8qi (v8qi, v8qi);
v4hi __builtin_vis_fexpand (v4qi);
__builtin_vis_fmul8x16 (v4qi, v4hi);
__builtin_vis_fmul8x16au (v4qi, v2hi);
__builtin_vis_fmul8x16al (v4qi, v2hi);
__builtin_vis_fmul8sux16 (v8qi, v4hi);
__builtin_vis_fmul8ulx16 (v8qi, v4hi);
__builtin_vis_fmuld8sux16 (v4qi, v2hi);
__builtin_vis_fmuld8ulx16 (v4qi, v2hi);
__builtin_vis_fpack16 (v4hi);
__builtin_vis_fpack32 (v2si, v8qi);
__builtin_vis_fpackfix (v2si);
__builtin_vis_fpmerge (v4qi, v4qi);
int64_t __builtin_vis_pdist (v8qi, v8qi, int64_t);
__builtin_vis_edge8 (void *, void *);
__builtin_vis_edge8l (void *, void *);
__builtin_vis_edge16 (void *, void *);
__builtin_vis_edge16l (void *, void *);
__builtin_vis_edge32 (void *, void *);
__builtin_vis_edge32l (void *, void *);
__builtin_vis_fpadd16 (v4hi, v4hi);
__builtin_vis_fpadd16s (v2hi, v2hi);
__builtin_vis_fpadd32 (v2si, v2si);
__builtin_vis_fpadd32s (v1si, v1si);
__builtin_vis_fpsub16 (v4hi, v4hi);
__builtin_vis_fpsub16s (v2hi, v2hi);
__builtin_vis_fpsub32 (v2si, v2si);
__builtin_vis_fpsub32s (v1si, v1si);
long __builtin_vis_array8 (long, long);
long __builtin_vis_array16 (long, long);
long __builtin_vis_array32 (long, long);
long __builtin_vis_bmask (long, long);
int64_t __builtin_vis_bshuffledi (int64_t, int64_t);
v2si __builtin_vis_bshufflev2si (v2si, v2si);
v4hi __builtin_vis_bshufflev2si (v4hi, v4hi);
v8qi __builtin_vis_bshufflev2si (v8qi, v8qi);
__builtin_vis_edge8n (void *, void *);
__builtin_vis_edge8ln (void *, void *);
__builtin_vis_edge16n (void *, void *);
__builtin_vis_edge16ln (void *, void *);
__builtin_vis_edge32n (void *, void *);
__builtin_vis_edge32ln (void *, void *);
void __builtin_vis_cmask8 (long);
void __builtin_vis_cmask16 (long);
void __builtin_vis_cmask32 (long);
v4hi __builtin_vis_fchksm16 (v4hi, v4hi);
__builtin_vis_fsll16 (v4hi, v4hi);
__builtin_vis_fslas16 (v4hi, v4hi);
__builtin_vis_fsrl16 (v4hi, v4hi);
__builtin_vis_fsra16 (v4hi, v4hi);
__builtin_vis_fsll16 (v2si, v2si);
__builtin_vis_fslas16 (v2si, v2si);
__builtin_vis_fsrl16 (v2si, v2si);
__builtin_vis_fsra16 (v2si, v2si);
long __builtin_vis_pdistn (v8qi, v8qi);
v4hi __builtin_vis_fmean16 (v4hi, v4hi);
int64_t __builtin_vis_fpadd64 (int64_t, int64_t);
int64_t __builtin_vis_fpsub64 (int64_t, int64_t);
__builtin_vis_fpadds16 (v4hi, v4hi);
__builtin_vis_fpadds16s (v2hi, v2hi);
__builtin_vis_fpsubs16 (v4hi, v4hi);
__builtin_vis_fpsubs16s (v2hi, v2hi);
__builtin_vis_fpadds32 (v2si, v2si);
__builtin_vis_fpadds32s (v1si, v1si);
__builtin_vis_fpsubs32 (v2si, v2si);
__builtin_vis_fpsubs32s (v1si, v1si);
float __builtin_vis_fhadds (float, float);
double __builtin_vis_fhaddd (double, double);
float __builtin_vis_fhsubs (float, float);
double __builtin_vis_fhsubd (double, double);
float __builtin_vis_fnhadds (float, float);
double __builtin_vis_fnhaddd (double, double);
int64_t __builtin_vis_umulxhi (int64_t, int64_t);
int64_t __builtin_vis_xmulx (int64_t, int64_t);
int64_t __builtin_vis_xmulxhi (int64_t, int64_t);
__float128 __builtin_fabsq (__float128)
__float128 __builtin_copysignq (__float128, __float128)
void __builtin_ia32_pause (void)
__float128 __builtin_infq (void)
__float128 __builtin_huge_valq (void)
void __builtin_cpu_init (void)
__builtin_cpu_init ();
if (__builtin_cpu_supports ("ssse3"))
int __builtin_cpu_is (const char *cpuname)
if (__builtin_cpu_is ("corei7"))
int __builtin_cpu_supports (const char *feature)
if (__builtin_cpu_supports ("popcnt"))
__builtin_ia32_paddb (v8qi, v8qi)
__builtin_ia32_paddw (v4hi, v4hi)
__builtin_ia32_paddd (v2si, v2si)
__builtin_ia32_psubb (v8qi, v8qi)
__builtin_ia32_psubw (v4hi, v4hi)
__builtin_ia32_psubd (v2si, v2si)
__builtin_ia32_paddsb (v8qi, v8qi)
__builtin_ia32_paddsw (v4hi, v4hi)
__builtin_ia32_psubsb (v8qi, v8qi)
__builtin_ia32_psubsw (v4hi, v4hi)
__builtin_ia32_paddusb (v8qi, v8qi)
v4hi __builtin_ia32_paddusw (v4hi, v4hi)
v8qi __builtin_ia32_psubusb (v8qi, v8qi)
v4hi __builtin_ia32_psubusw (v4hi, v4hi)
v4hi __builtin_ia32_pmullw (v4hi, v4hi)
v4hi __builtin_ia32_pmulhw (v4hi, v4hi)
di __builtin_ia32_pand (di, di)
di __builtin_ia32_pandn (di,di)
di __builtin_ia32_por (di, di)
di __builtin_ia32_pxor (di, di)
v8qi __builtin_ia32_pcmpeqb (v8qi, v8qi)
v4hi __builtin_ia32_pcmpeqw (v4hi, v4hi)
v2si __builtin_ia32_pcmpeqd (v2si, v2si)
v8qi __builtin_ia32_pcmpgtb (v8qi, v8qi)
v4hi __builtin_ia32_pcmpgtw (v4hi, v4hi)
v2si __builtin_ia32_pcmpgtd (v2si, v2si)
v8qi __builtin_ia32_punpckhbw (v8qi, v8qi)
v4hi __builtin_ia32_punpckhwd (v4hi, v4hi)
v2si __builtin_ia32_punpckhdq (v2si, v2si)
v8qi __builtin_ia32_punpcklbw (v8qi, v8qi)
v4hi __builtin_ia32_punpcklwd (v4hi, v4hi)
v2si __builtin_ia32_punpckldq (v2si, v2si)
v8qi __builtin_ia32_packsswb (v4hi, v4hi)
v4hi __builtin_ia32_packssdw (v2si, v2si)
v8qi __builtin_ia32_packuswb (v4hi, v4hi)
__builtin_ia32_psllw (v4hi, v4hi)
__builtin_ia32_pslld (v2si, v2si)
__builtin_ia32_psllq (v1di, v1di)
__builtin_ia32_psrlw (v4hi, v4hi)
__builtin_ia32_psrld (v2si, v2si)
__builtin_ia32_psrlq (v1di, v1di)
__builtin_ia32_psraw (v4hi, v4hi)
__builtin_ia32_psrad (v2si, v2si)
__builtin_ia32_psllwi (v4hi, int)
__builtin_ia32_pslldi (v2si, int)
__builtin_ia32_psllqi (v1di, int)
__builtin_ia32_psrlwi (v4hi, int)
__builtin_ia32_psrldi (v2si, int)
__builtin_ia32_psrlqi (v1di, int)
__builtin_ia32_psrawi (v4hi, int)
__builtin_ia32_psradi (v2si, int)
v4hi __builtin_ia32_pmulhuw (v4hi, v4hi)
v8qi __builtin_ia32_pavgb (v8qi, v8qi)
v4hi __builtin_ia32_pavgw (v4hi, v4hi)
v1di __builtin_ia32_psadbw (v8qi, v8qi)
v8qi __builtin_ia32_pmaxub (v8qi, v8qi)
v4hi __builtin_ia32_pmaxsw (v4hi, v4hi)
v8qi __builtin_ia32_pminub (v8qi, v8qi)
v4hi __builtin_ia32_pminsw (v4hi, v4hi)
int __builtin_ia32_pmovmskb (v8qi)
void __builtin_ia32_maskmovq (v8qi, v8qi, char *)
void __builtin_ia32_movntq (di *, di)
void __builtin_ia32_sfence (void)
int __builtin_ia32_comieq (v4sf, v4sf)
int __builtin_ia32_comineq (v4sf, v4sf)
int __builtin_ia32_comilt (v4sf, v4sf)
int __builtin_ia32_comile (v4sf, v4sf)
int __builtin_ia32_comigt (v4sf, v4sf)
int __builtin_ia32_comige (v4sf, v4sf)
int __builtin_ia32_ucomieq (v4sf, v4sf)
int __builtin_ia32_ucomineq (v4sf, v4sf)
int __builtin_ia32_ucomilt (v4sf, v4sf)
int __builtin_ia32_ucomile (v4sf, v4sf)
int __builtin_ia32_ucomigt (v4sf, v4sf)
int __builtin_ia32_ucomige (v4sf, v4sf)
v4sf __builtin_ia32_addps (v4sf, v4sf)
v4sf __builtin_ia32_subps (v4sf, v4sf)
v4sf __builtin_ia32_mulps (v4sf, v4sf)
v4sf __builtin_ia32_divps (v4sf, v4sf)
v4sf __builtin_ia32_addss (v4sf, v4sf)
v4sf __builtin_ia32_subss (v4sf, v4sf)
v4sf __builtin_ia32_mulss (v4sf, v4sf)
v4sf __builtin_ia32_divss (v4sf, v4sf)
v4sf __builtin_ia32_cmpeqps (v4sf, v4sf)
v4sf __builtin_ia32_cmpltps (v4sf, v4sf)
v4sf __builtin_ia32_cmpleps (v4sf, v4sf)
v4sf __builtin_ia32_cmpgtps (v4sf, v4sf)
v4sf __builtin_ia32_cmpgeps (v4sf, v4sf)
v4sf __builtin_ia32_cmpunordps (v4sf, v4sf)
v4sf __builtin_ia32_cmpneqps (v4sf, v4sf)
v4sf __builtin_ia32_cmpnltps (v4sf, v4sf)
v4sf __builtin_ia32_cmpnleps (v4sf, v4sf)
v4sf __builtin_ia32_cmpngtps (v4sf, v4sf)
v4sf __builtin_ia32_cmpngeps (v4sf, v4sf)
v4sf __builtin_ia32_cmpordps (v4sf, v4sf)
v4sf __builtin_ia32_cmpeqss (v4sf, v4sf)
v4sf __builtin_ia32_cmpltss (v4sf, v4sf)
v4sf __builtin_ia32_cmpless (v4sf, v4sf)
v4sf __builtin_ia32_cmpunordss (v4sf, v4sf)
v4sf __builtin_ia32_cmpneqss (v4sf, v4sf)
v4sf __builtin_ia32_cmpnltss (v4sf, v4sf)
v4sf __builtin_ia32_cmpnless (v4sf, v4sf)
v4sf __builtin_ia32_cmpordss (v4sf, v4sf)
v4sf __builtin_ia32_maxps (v4sf, v4sf)
v4sf __builtin_ia32_maxss (v4sf, v4sf)
v4sf __builtin_ia32_minps (v4sf, v4sf)
v4sf __builtin_ia32_minss (v4sf, v4sf)
v4sf __builtin_ia32_andps (v4sf, v4sf)
v4sf __builtin_ia32_andnps (v4sf, v4sf)
v4sf __builtin_ia32_orps (v4sf, v4sf)
v4sf __builtin_ia32_xorps (v4sf, v4sf)
v4sf __builtin_ia32_movss (v4sf, v4sf)
v4sf __builtin_ia32_movhlps (v4sf, v4sf)
v4sf __builtin_ia32_movlhps (v4sf, v4sf)
v4sf __builtin_ia32_unpckhps (v4sf, v4sf)
v4sf __builtin_ia32_unpcklps (v4sf, v4sf)
v4sf __builtin_ia32_cvtpi2ps (v4sf, v2si)
v4sf __builtin_ia32_cvtsi2ss (v4sf, int)
v2si __builtin_ia32_cvtps2pi (v4sf)
int __builtin_ia32_cvtss2si (v4sf)
v2si __builtin_ia32_cvttps2pi (v4sf)
int __builtin_ia32_cvttss2si (v4sf)
v4sf __builtin_ia32_rcpps (v4sf)
v4sf __builtin_ia32_rsqrtps (v4sf)
v4sf __builtin_ia32_sqrtps (v4sf)
v4sf __builtin_ia32_rcpss (v4sf)
v4sf __builtin_ia32_rsqrtss (v4sf)
v4sf __builtin_ia32_sqrtss (v4sf)
v4sf __builtin_ia32_shufps (v4sf, v4sf, int)
void __builtin_ia32_movntps (float *, v4sf)
int __builtin_ia32_movmskps (v4sf)
v4sf __builtin_ia32_loadups (float *)
void __builtin_ia32_storeups (float *, v4sf)
v4sf __builtin_ia32_loadss (float *)
v4sf __builtin_ia32_loadhps (v4sf, const v2sf *)
v4sf __builtin_ia32_loadlps (v4sf, const v2sf *)
void __builtin_ia32_storehps (v2sf *, v4sf)
void __builtin_ia32_storelps (v2sf *, v4sf)
int __builtin_ia32_comisdeq (v2df, v2df)
int __builtin_ia32_comisdlt (v2df, v2df)
int __builtin_ia32_comisdle (v2df, v2df)
int __builtin_ia32_comisdgt (v2df, v2df)
int __builtin_ia32_comisdge (v2df, v2df)
int __builtin_ia32_comisdneq (v2df, v2df)
int __builtin_ia32_ucomisdeq (v2df, v2df)
int __builtin_ia32_ucomisdlt (v2df, v2df)
int __builtin_ia32_ucomisdle (v2df, v2df)
int __builtin_ia32_ucomisdgt (v2df, v2df)
int __builtin_ia32_ucomisdge (v2df, v2df)
int __builtin_ia32_ucomisdneq (v2df, v2df)
v2df __builtin_ia32_cmpeqpd (v2df, v2df)
v2df __builtin_ia32_cmpltpd (v2df, v2df)
v2df __builtin_ia32_cmplepd (v2df, v2df)
v2df __builtin_ia32_cmpgtpd (v2df, v2df)
v2df __builtin_ia32_cmpgepd (v2df, v2df)
v2df __builtin_ia32_cmpunordpd (v2df, v2df)
v2df __builtin_ia32_cmpneqpd (v2df, v2df)
v2df __builtin_ia32_cmpnltpd (v2df, v2df)
v2df __builtin_ia32_cmpnlepd (v2df, v2df)
v2df __builtin_ia32_cmpngtpd (v2df, v2df)
v2df __builtin_ia32_cmpngepd (v2df, v2df)
v2df __builtin_ia32_cmpordpd (v2df, v2df)
v2df __builtin_ia32_cmpeqsd (v2df, v2df)
v2df __builtin_ia32_cmpltsd (v2df, v2df)
v2df __builtin_ia32_cmplesd (v2df, v2df)
v2df __builtin_ia32_cmpunordsd (v2df, v2df)
v2df __builtin_ia32_cmpneqsd (v2df, v2df)
v2df __builtin_ia32_cmpnltsd (v2df, v2df)
v2df __builtin_ia32_cmpnlesd (v2df, v2df)
v2df __builtin_ia32_cmpordsd (v2df, v2df)
v2di __builtin_ia32_paddq (v2di, v2di)
v2di __builtin_ia32_psubq (v2di, v2di)
v2df __builtin_ia32_addpd (v2df, v2df)
v2df __builtin_ia32_subpd (v2df, v2df)
v2df __builtin_ia32_mulpd (v2df, v2df)
v2df __builtin_ia32_divpd (v2df, v2df)
v2df __builtin_ia32_addsd (v2df, v2df)
v2df __builtin_ia32_subsd (v2df, v2df)
v2df __builtin_ia32_mulsd (v2df, v2df)
v2df __builtin_ia32_divsd (v2df, v2df)
v2df __builtin_ia32_minpd (v2df, v2df)
v2df __builtin_ia32_maxpd (v2df, v2df)
v2df __builtin_ia32_minsd (v2df, v2df)
v2df __builtin_ia32_maxsd (v2df, v2df)
v2df __builtin_ia32_andpd (v2df, v2df)
v2df __builtin_ia32_andnpd (v2df, v2df)
v2df __builtin_ia32_orpd (v2df, v2df)
v2df __builtin_ia32_xorpd (v2df, v2df)
v2df __builtin_ia32_movsd (v2df, v2df)
v2df __builtin_ia32_unpckhpd (v2df, v2df)
v2df __builtin_ia32_unpcklpd (v2df, v2df)
v16qi __builtin_ia32_paddb128 (v16qi, v16qi)
v8hi __builtin_ia32_paddw128 (v8hi, v8hi)
v4si __builtin_ia32_paddd128 (v4si, v4si)
v2di __builtin_ia32_paddq128 (v2di, v2di)
v16qi __builtin_ia32_psubb128 (v16qi, v16qi)
v8hi __builtin_ia32_psubw128 (v8hi, v8hi)
v4si __builtin_ia32_psubd128 (v4si, v4si)
v2di __builtin_ia32_psubq128 (v2di, v2di)
v8hi __builtin_ia32_pmullw128 (v8hi, v8hi)
v8hi __builtin_ia32_pmulhw128 (v8hi, v8hi)
v2di __builtin_ia32_pand128 (v2di, v2di)
v2di __builtin_ia32_pandn128 (v2di, v2di)
v2di __builtin_ia32_por128 (v2di, v2di)
v2di __builtin_ia32_pxor128 (v2di, v2di)
v16qi __builtin_ia32_pavgb128 (v16qi, v16qi)
v8hi __builtin_ia32_pavgw128 (v8hi, v8hi)
v16qi __builtin_ia32_pcmpeqb128 (v16qi, v16qi)
v8hi __builtin_ia32_pcmpeqw128 (v8hi, v8hi)
v4si __builtin_ia32_pcmpeqd128 (v4si, v4si)
v16qi __builtin_ia32_pcmpgtb128 (v16qi, v16qi)
v8hi __builtin_ia32_pcmpgtw128 (v8hi, v8hi)
v4si __builtin_ia32_pcmpgtd128 (v4si, v4si)
v16qi __builtin_ia32_pmaxub128 (v16qi, v16qi)
v8hi __builtin_ia32_pmaxsw128 (v8hi, v8hi)
v16qi __builtin_ia32_pminub128 (v16qi, v16qi)
v8hi __builtin_ia32_pminsw128 (v8hi, v8hi)
v16qi __builtin_ia32_punpckhbw128 (v16qi, v16qi)
v8hi __builtin_ia32_punpckhwd128 (v8hi, v8hi)
v4si __builtin_ia32_punpckhdq128 (v4si, v4si)
v2di __builtin_ia32_punpckhqdq128 (v2di, v2di)
v16qi __builtin_ia32_punpcklbw128 (v16qi, v16qi)
v8hi __builtin_ia32_punpcklwd128 (v8hi, v8hi)
v4si __builtin_ia32_punpckldq128 (v4si, v4si)
v2di __builtin_ia32_punpcklqdq128 (v2di, v2di)
v16qi __builtin_ia32_packsswb128 (v8hi, v8hi)
v8hi __builtin_ia32_packssdw128 (v4si, v4si)
v16qi __builtin_ia32_packuswb128 (v8hi, v8hi)
v8hi __builtin_ia32_pmulhuw128 (v8hi, v8hi)
void __builtin_ia32_maskmovdqu (v16qi, v16qi)
v2df __builtin_ia32_loadupd (double *)
void __builtin_ia32_storeupd (double *, v2df)
v2df __builtin_ia32_loadhpd (v2df, double const *)
v2df __builtin_ia32_loadlpd (v2df, double const *)
int __builtin_ia32_movmskpd (v2df)
int __builtin_ia32_pmovmskb128 (v16qi)
void __builtin_ia32_movnti (int *, int)
void __builtin_ia32_movnti64 (long long int *, long long int)
void __builtin_ia32_movntpd (double *, v2df)
void __builtin_ia32_movntdq (v2df *, v2df)
v4si __builtin_ia32_pshufd (v4si, int)
v8hi __builtin_ia32_pshuflw (v8hi, int)
v8hi __builtin_ia32_pshufhw (v8hi, int)
v2di __builtin_ia32_psadbw128 (v16qi, v16qi)
v2df __builtin_ia32_sqrtpd (v2df)
v2df __builtin_ia32_sqrtsd (v2df)
v2df __builtin_ia32_shufpd (v2df, v2df, int)
v2df __builtin_ia32_cvtdq2pd (v4si)
v4sf __builtin_ia32_cvtdq2ps (v4si)
v4si __builtin_ia32_cvtpd2dq (v2df)
v2si __builtin_ia32_cvtpd2pi (v2df)
v4sf __builtin_ia32_cvtpd2ps (v2df)
v4si __builtin_ia32_cvttpd2dq (v2df)
v2si __builtin_ia32_cvttpd2pi (v2df)
v2df __builtin_ia32_cvtpi2pd (v2si)
int __builtin_ia32_cvtsd2si (v2df)
int __builtin_ia32_cvttsd2si (v2df)
long long __builtin_ia32_cvtsd2si64 (v2df)
long long __builtin_ia32_cvttsd2si64 (v2df)
v4si __builtin_ia32_cvtps2dq (v4sf)
v2df __builtin_ia32_cvtps2pd (v4sf)
v4si __builtin_ia32_cvttps2dq (v4sf)
v2df __builtin_ia32_cvtsi2sd (v2df, int)
v2df __builtin_ia32_cvtsi642sd (v2df, long long)
v4sf __builtin_ia32_cvtsd2ss (v4sf, v2df)
v2df __builtin_ia32_cvtss2sd (v2df, v4sf)
void __builtin_ia32_clflush (const void *)
void __builtin_ia32_lfence (void)
void __builtin_ia32_mfence (void)
v16qi __builtin_ia32_loaddqu (const char *)
void __builtin_ia32_storedqu (char *, v16qi)
v1di __builtin_ia32_pmuludq (v2si, v2si)
v2di __builtin_ia32_pmuludq128 (v4si, v4si)
v8hi __builtin_ia32_psllw128 (v8hi, v8hi)
__builtin_ia32_pslld128 (v4si, v4si)
__builtin_ia32_psllq128 (v2di, v2di)
__builtin_ia32_psrlw128 (v8hi, v8hi)
__builtin_ia32_psrld128 (v4si, v4si)
__builtin_ia32_psrlq128 (v2di, v2di)
__builtin_ia32_psraw128 (v8hi, v8hi)
__builtin_ia32_psrad128 (v4si, v4si)
__builtin_ia32_pslldqi128 (v2di, int)
__builtin_ia32_psllwi128 (v8hi, int)
__builtin_ia32_pslldi128 (v4si, int)
__builtin_ia32_psllqi128 (v2di, int)
__builtin_ia32_psrldqi128 (v2di, int)
__builtin_ia32_psrlwi128 (v8hi, int)
__builtin_ia32_psrldi128 (v4si, int)
__builtin_ia32_psrlqi128 (v2di, int)
__builtin_ia32_psrawi128 (v8hi, int)
__builtin_ia32_psradi128 (v4si, int)
__builtin_ia32_pmaddwd128 (v8hi, v8hi)
__builtin_ia32_movq128 (v2di)
v2df __builtin_ia32_addsubpd (v2df, v2df)
v4sf __builtin_ia32_addsubps (v4sf, v4sf)
v2df __builtin_ia32_haddpd (v2df, v2df)
v4sf __builtin_ia32_haddps (v4sf, v4sf)
v2df __builtin_ia32_hsubpd (v2df, v2df)
v4sf __builtin_ia32_hsubps (v4sf, v4sf)
v16qi __builtin_ia32_lddqu (char const *)
void __builtin_ia32_monitor (void *, unsigned int, unsigned int)
v4sf __builtin_ia32_movshdup (v4sf)
v4sf __builtin_ia32_movsldup (v4sf)
void __builtin_ia32_mwait (unsigned int, unsigned int)
__builtin_ia32_phaddd (v2si, v2si)
__builtin_ia32_phaddw (v4hi, v4hi)
__builtin_ia32_phaddsw (v4hi, v4hi)
__builtin_ia32_phsubd (v2si, v2si)
__builtin_ia32_phsubw (v4hi, v4hi)
__builtin_ia32_phsubsw (v4hi, v4hi)
__builtin_ia32_pmaddubsw (v8qi, v8qi)
__builtin_ia32_pmulhrsw (v4hi, v4hi)
__builtin_ia32_pshufb (v8qi, v8qi)
__builtin_ia32_psignb (v8qi, v8qi)
__builtin_ia32_psignd (v2si, v2si)
__builtin_ia32_psignw (v4hi, v4hi)
__builtin_ia32_palignr (v1di, v1di, int)
__builtin_ia32_pabsb (v8qi)
__builtin_ia32_pabsd (v2si)
__builtin_ia32_pabsw (v4hi)
v4si __builtin_ia32_phaddd128 (v4si, v4si)
v8hi __builtin_ia32_phaddw128 (v8hi, v8hi)
v8hi __builtin_ia32_phaddsw128 (v8hi, v8hi)
v4si __builtin_ia32_phsubd128 (v4si, v4si)
v8hi __builtin_ia32_phsubw128 (v8hi, v8hi)
v8hi __builtin_ia32_phsubsw128 (v8hi, v8hi)
v8hi __builtin_ia32_pmaddubsw128 (v16qi, v16qi)
v8hi __builtin_ia32_pmulhrsw128 (v8hi, v8hi)
v16qi __builtin_ia32_pshufb128 (v16qi, v16qi)
v16qi __builtin_ia32_psignb128 (v16qi, v16qi)
v4si __builtin_ia32_psignd128 (v4si, v4si)
v8hi __builtin_ia32_psignw128 (v8hi, v8hi)
v2di __builtin_ia32_palignr128 (v2di, v2di, int)
v16qi __builtin_ia32_pabsb128 (v16qi)
v4si __builtin_ia32_pabsd128 (v4si)
v8hi __builtin_ia32_pabsw128 (v8hi)
v2df __builtin_ia32_blendpd (v2df, v2df, const int)
v4sf __builtin_ia32_blendps (v4sf, v4sf, const int)
v2df __builtin_ia32_blendvpd (v2df, v2df, v2df)
v4sf __builtin_ia32_blendvps (v4sf, v4sf, v4sf)
v2df __builtin_ia32_dppd (v2df, v2df, const int)
v4sf __builtin_ia32_dpps (v4sf, v4sf, const int)
v4sf __builtin_ia32_insertps128 (v4sf, v4sf, const int)
v2di __builtin_ia32_movntdqa (v2di *);
v16qi __builtin_ia32_mpsadbw128 (v16qi, v16qi, const int)
v8hi __builtin_ia32_packusdw128 (v4si, v4si)
v16qi __builtin_ia32_pblendvb128 (v16qi, v16qi, v16qi)
v8hi __builtin_ia32_pblendw128 (v8hi, v8hi, const int)
v2di __builtin_ia32_pcmpeqq (v2di, v2di)
v8hi __builtin_ia32_phminposuw128 (v8hi)
v16qi __builtin_ia32_pmaxsb128 (v16qi, v16qi)
v4si __builtin_ia32_pmaxsd128 (v4si, v4si)
v4si __builtin_ia32_pmaxud128 (v4si, v4si)
v8hi __builtin_ia32_pmaxuw128 (v8hi, v8hi)
v16qi __builtin_ia32_pminsb128 (v16qi, v16qi)
v4si __builtin_ia32_pminsd128 (v4si, v4si)
v4si __builtin_ia32_pminud128 (v4si, v4si)
v8hi __builtin_ia32_pminuw128 (v8hi, v8hi)
v4si __builtin_ia32_pmovsxbd128 (v16qi)
v2di __builtin_ia32_pmovsxbq128 (v16qi)
v8hi __builtin_ia32_pmovsxbw128 (v16qi)
v2di __builtin_ia32_pmovsxdq128 (v4si)
v4si __builtin_ia32_pmovsxwd128 (v8hi)
v2di __builtin_ia32_pmovsxwq128 (v8hi)
v4si __builtin_ia32_pmovzxbd128 (v16qi)
v2di __builtin_ia32_pmovzxbq128 (v16qi)
v8hi __builtin_ia32_pmovzxbw128 (v16qi)
v2di __builtin_ia32_pmovzxdq128 (v4si)
v4si __builtin_ia32_pmovzxwd128 (v8hi)
v2di __builtin_ia32_pmovzxwq128 (v8hi)
v2di __builtin_ia32_pmuldq128 (v4si, v4si)
v4si __builtin_ia32_pmulld128 (v4si, v4si)
int __builtin_ia32_ptestc128 (v2di, v2di)
int __builtin_ia32_ptestnzc128 (v2di, v2di)
int __builtin_ia32_ptestz128 (v2di, v2di)
v2df __builtin_ia32_roundpd (v2df, const int)
v4sf __builtin_ia32_roundps (v4sf, const int)
v2df __builtin_ia32_roundsd (v2df, v2df, const int)
v4sf __builtin_ia32_roundss (v4sf, v4sf, const int)
v4sf __builtin_ia32_vec_set_v4sf (v4sf, float, const int)
int __builtin_ia32_vec_ext_v16qi (v16qi, const int)
v16qi __builtin_ia32_vec_set_v16qi (v16qi, int, const int)
v4si __builtin_ia32_vec_set_v4si (v4si, int, const int)
v2di __builtin_ia32_vec_set_v2di (v2di, long long, const int)
float __builtin_ia32_vec_ext_v4sf (v4sf, const int)
int __builtin_ia32_vec_ext_v4si (v4si, const int)
long long __builtin_ia32_vec_ext_v2di (v2di, const int)
v16qi __builtin_ia32_pcmpestrm128 (v16qi, int, v16qi, int, const int)
int __builtin_ia32_pcmpestri128 (v16qi, int, v16qi, int, const int)
int __builtin_ia32_pcmpestria128 (v16qi, int, v16qi, int, const int)
int __builtin_ia32_pcmpestric128 (v16qi, int, v16qi, int, const int)
int __builtin_ia32_pcmpestrio128 (v16qi, int, v16qi, int, const int)
int __builtin_ia32_pcmpestris128 (v16qi, int, v16qi, int, const int)
int __builtin_ia32_pcmpestriz128 (v16qi, int, v16qi, int, const int)
v16qi __builtin_ia32_pcmpistrm128 (v16qi, v16qi, const int)
int __builtin_ia32_pcmpistri128 (v16qi, v16qi, const int)
int __builtin_ia32_pcmpistria128 (v16qi, v16qi, const int)
int __builtin_ia32_pcmpistric128 (v16qi, v16qi, const int)
int __builtin_ia32_pcmpistrio128 (v16qi, v16qi, const int)
int __builtin_ia32_pcmpistris128 (v16qi, v16qi, const int)
int __builtin_ia32_pcmpistriz128 (v16qi, v16qi, const int)
v2di __builtin_ia32_pcmpgtq (v2di, v2di)
unsigned int __builtin_ia32_crc32qi (unsigned int, unsigned char)
unsigned int __builtin_ia32_crc32hi (unsigned int, unsigned short)
unsigned int __builtin_ia32_crc32si (unsigned int, unsigned int)
unsigned long long __builtin_ia32_crc32di (unsigned long long, unsigned long
int __builtin_popcount (unsigned int)
int __builtin_popcountl (unsigned long)
int __builtin_popcountll (unsigned long long)
v4df __builtin_ia32_addpd256 (v4df,v4df)
v8sf __builtin_ia32_addps256 (v8sf,v8sf)
v4df __builtin_ia32_addsubpd256 (v4df,v4df)
v8sf __builtin_ia32_addsubps256 (v8sf,v8sf)
v4df __builtin_ia32_andnpd256 (v4df,v4df)
v8sf __builtin_ia32_andnps256 (v8sf,v8sf)
v4df __builtin_ia32_andpd256 (v4df,v4df)
v8sf __builtin_ia32_andps256 (v8sf,v8sf)
v4df __builtin_ia32_blendpd256 (v4df,v4df,int)
v8sf __builtin_ia32_blendps256 (v8sf,v8sf,int)
v4df __builtin_ia32_blendvpd256 (v4df,v4df,v4df)
v8sf __builtin_ia32_blendvps256 (v8sf,v8sf,v8sf)
v2df __builtin_ia32_cmppd (v2df,v2df,int)
v4df __builtin_ia32_cmppd256 (v4df,v4df,int)
v4sf __builtin_ia32_cmpps (v4sf,v4sf,int)
v8sf __builtin_ia32_cmpps256 (v8sf,v8sf,int)
v2df __builtin_ia32_cmpsd (v2df,v2df,int)
v4sf __builtin_ia32_cmpss (v4sf,v4sf,int)
v4df __builtin_ia32_cvtdq2pd256 (v4si)
v8sf __builtin_ia32_cvtdq2ps256 (v8si)
v4si __builtin_ia32_cvtpd2dq256 (v4df)
v4sf __builtin_ia32_cvtpd2ps256 (v4df)
v8si __builtin_ia32_cvtps2dq256 (v8sf)
v4df __builtin_ia32_cvtps2pd256 (v4sf)
v4si __builtin_ia32_cvttpd2dq256 (v4df)
v8si __builtin_ia32_cvttps2dq256 (v8sf)
v4df __builtin_ia32_divpd256 (v4df,v4df)
v8sf __builtin_ia32_divps256 (v8sf,v8sf)
v8sf __builtin_ia32_dpps256 (v8sf,v8sf,int)
v4df __builtin_ia32_haddpd256 (v4df,v4df)
v8sf __builtin_ia32_haddps256 (v8sf,v8sf)
v4df __builtin_ia32_hsubpd256 (v4df,v4df)
v8sf __builtin_ia32_hsubps256 (v8sf,v8sf)
v32qi __builtin_ia32_lddqu256 (pcchar)
v32qi __builtin_ia32_loaddqu256 (pcchar)
v4df __builtin_ia32_loadupd256 (pcdouble)
v8sf __builtin_ia32_loadups256 (pcfloat)
v2df __builtin_ia32_maskloadpd (pcv2df,v2df)
v4df __builtin_ia32_maskloadpd256 (pcv4df,v4df)
v4sf __builtin_ia32_maskloadps (pcv4sf,v4sf)
v8sf __builtin_ia32_maskloadps256 (pcv8sf,v8sf)
void __builtin_ia32_maskstorepd (pv2df,v2df,v2df)
void __builtin_ia32_maskstorepd256 (pv4df,v4df,v4df)
void __builtin_ia32_maskstoreps (pv4sf,v4sf,v4sf)
void __builtin_ia32_maskstoreps256 (pv8sf,v8sf,v8sf)
v4df __builtin_ia32_maxpd256 (v4df,v4df)
v8sf __builtin_ia32_maxps256 (v8sf,v8sf)
v4df __builtin_ia32_minpd256 (v4df,v4df)
v8sf __builtin_ia32_minps256 (v8sf,v8sf)
v4df __builtin_ia32_movddup256 (v4df)
int __builtin_ia32_movmskpd256 (v4df)
int __builtin_ia32_movmskps256 (v8sf)
v8sf __builtin_ia32_movshdup256 (v8sf)
v8sf __builtin_ia32_movsldup256 (v8sf)
v4df __builtin_ia32_mulpd256 (v4df,v4df)
v8sf __builtin_ia32_mulps256 (v8sf,v8sf)
v4df __builtin_ia32_orpd256 (v4df,v4df)
v8sf __builtin_ia32_orps256 (v8sf,v8sf)
v2df __builtin_ia32_pd_pd256 (v4df)
v4df __builtin_ia32_pd256_pd (v2df)
v4sf __builtin_ia32_ps_ps256 (v8sf)
v8sf __builtin_ia32_ps256_ps (v4sf)
int __builtin_ia32_ptestc256 (v4di,v4di,ptest)
int __builtin_ia32_ptestnzc256 (v4di,v4di,ptest)
int __builtin_ia32_ptestz256 (v4di,v4di,ptest)
v8sf __builtin_ia32_rcpps256 (v8sf)
v4df __builtin_ia32_roundpd256 (v4df,int)
v8sf __builtin_ia32_roundps256 (v8sf,int)
v8sf __builtin_ia32_rsqrtps_nr256 (v8sf)
v8sf __builtin_ia32_rsqrtps256 (v8sf)
v4df __builtin_ia32_shufpd256 (v4df,v4df,int)
v8sf __builtin_ia32_shufps256 (v8sf,v8sf,int)
v4si __builtin_ia32_si_si256 (v8si)
v8si __builtin_ia32_si256_si (v4si)
v4df __builtin_ia32_sqrtpd256 (v4df)
v8sf __builtin_ia32_sqrtps_nr256 (v8sf)
v8sf __builtin_ia32_sqrtps256 (v8sf)
void __builtin_ia32_storedqu256 (pchar,v32qi)
void __builtin_ia32_storeupd256 (pdouble,v4df)
void __builtin_ia32_storeups256 (pfloat,v8sf)
v4df __builtin_ia32_subpd256 (v4df,v4df)
v8sf __builtin_ia32_subps256 (v8sf,v8sf)
v4df __builtin_ia32_unpckhpd256 (v4df,v4df)
v8sf __builtin_ia32_unpckhps256 (v8sf,v8sf)
v4df __builtin_ia32_unpcklpd256 (v4df,v4df)
v8sf __builtin_ia32_unpcklps256 (v8sf,v8sf)
v4df __builtin_ia32_vbroadcastf128_pd256 (pcv2df)
v8sf __builtin_ia32_vbroadcastf128_ps256 (pcv4sf)
v4df __builtin_ia32_vbroadcastsd256 (pcdouble)
v4sf __builtin_ia32_vbroadcastss (pcfloat)
v8sf __builtin_ia32_vbroadcastss256 (pcfloat)
v2df __builtin_ia32_vextractf128_pd256 (v4df,int)
v4sf __builtin_ia32_vextractf128_ps256 (v8sf,int)
v4si __builtin_ia32_vextractf128_si256 (v8si,int)
v4df __builtin_ia32_vinsertf128_pd256 (v4df,v2df,int)
v8sf __builtin_ia32_vinsertf128_ps256 (v8sf,v4sf,int)
v8si __builtin_ia32_vinsertf128_si256 (v8si,v4si,int)
v4df __builtin_ia32_vperm2f128_pd256 (v4df,v4df,int)
v8sf __builtin_ia32_vperm2f128_ps256 (v8sf,v8sf,int)
v8si __builtin_ia32_vperm2f128_si256 (v8si,v8si,int)
v2df __builtin_ia32_vpermil2pd (v2df,v2df,v2di,int)
v4df __builtin_ia32_vpermil2pd256 (v4df,v4df,v4di,int)
v4sf __builtin_ia32_vpermil2ps (v4sf,v4sf,v4si,int)
v8sf __builtin_ia32_vpermil2ps256 (v8sf,v8sf,v8si,int)
v2df __builtin_ia32_vpermilpd (v2df,int)
v4df __builtin_ia32_vpermilpd256 (v4df,int)
v4sf __builtin_ia32_vpermilps (v4sf,int)
v8sf __builtin_ia32_vpermilps256 (v8sf,int)
v2df __builtin_ia32_vpermilvarpd (v2df,v2di)
v4df __builtin_ia32_vpermilvarpd256 (v4df,v4di)
v4sf __builtin_ia32_vpermilvarps (v4sf,v4si)
v8sf __builtin_ia32_vpermilvarps256 (v8sf,v8si)
int __builtin_ia32_vtestcpd (v2df,v2df,ptest)
int __builtin_ia32_vtestcpd256 (v4df,v4df,ptest)
int __builtin_ia32_vtestcps (v4sf,v4sf,ptest)
int __builtin_ia32_vtestcps256 (v8sf,v8sf,ptest)
int __builtin_ia32_vtestnzcpd (v2df,v2df,ptest)
int __builtin_ia32_vtestnzcpd256 (v4df,v4df,ptest)
int __builtin_ia32_vtestnzcps (v4sf,v4sf,ptest)
int __builtin_ia32_vtestnzcps256 (v8sf,v8sf,ptest)
int __builtin_ia32_vtestzpd (v2df,v2df,ptest)
int __builtin_ia32_vtestzpd256 (v4df,v4df,ptest)
int __builtin_ia32_vtestzps (v4sf,v4sf,ptest)
int __builtin_ia32_vtestzps256 (v8sf,v8sf,ptest)
void __builtin_ia32_vzeroall (void)
void __builtin_ia32_vzeroupper (void)
v4df __builtin_ia32_xorpd256 (v4df,v4df)
v8sf __builtin_ia32_xorps256 (v8sf,v8sf)
v32qi __builtin_ia32_mpsadbw256 (v32qi,v32qi,int)
v32qi __builtin_ia32_pabsb256 (v32qi)
v16hi __builtin_ia32_pabsw256 (v16hi)
v8si __builtin_ia32_pabsd256 (v8si)
v16hi __builtin_ia32_packssdw256 (v8si,v8si)
v32qi __builtin_ia32_packsswb256 (v16hi,v16hi)
v16hi __builtin_ia32_packusdw256 (v8si,v8si)
v32qi __builtin_ia32_packuswb256 (v16hi,v16hi)
v32qi __builtin_ia32_paddb256 (v32qi,v32qi)
v16hi __builtin_ia32_paddw256 (v16hi,v16hi)
v8si __builtin_ia32_paddd256 (v8si,v8si)
v4di __builtin_ia32_paddq256 (v4di,v4di)
v32qi __builtin_ia32_paddsb256 (v32qi,v32qi)
v16hi __builtin_ia32_paddsw256 (v16hi,v16hi)
v32qi __builtin_ia32_paddusb256 (v32qi,v32qi)
v16hi __builtin_ia32_paddusw256 (v16hi,v16hi)
v4di __builtin_ia32_palignr256 (v4di,v4di,int)
v4di __builtin_ia32_andsi256 (v4di,v4di)
v4di __builtin_ia32_andnotsi256 (v4di,v4di)
v32qi __builtin_ia32_pavgb256 (v32qi,v32qi)
v16hi __builtin_ia32_pavgw256 (v16hi,v16hi)
v32qi __builtin_ia32_pblendvb256 (v32qi,v32qi,v32qi)
v16hi __builtin_ia32_pblendw256 (v16hi,v16hi,int)
v32qi __builtin_ia32_pcmpeqb256 (v32qi,v32qi)
v16hi __builtin_ia32_pcmpeqw256 (v16hi,v16hi)
v8si __builtin_ia32_pcmpeqd256 (c8si,v8si)
v4di __builtin_ia32_pcmpeqq256 (v4di,v4di)
v32qi __builtin_ia32_pcmpgtb256 (v32qi,v32qi)
v16hi __builtin_ia32_pcmpgtw256 (16hi,v16hi)
v8si __builtin_ia32_pcmpgtd256 (v8si,v8si)
v4di __builtin_ia32_pcmpgtq256 (v4di,v4di)
v16hi __builtin_ia32_phaddw256 (v16hi,v16hi)
v8si __builtin_ia32_phaddd256 (v8si,v8si)
v16hi __builtin_ia32_phaddsw256 (v16hi,v16hi)
v16hi __builtin_ia32_phsubw256 (v16hi,v16hi)
v8si __builtin_ia32_phsubd256 (v8si,v8si)
v16hi __builtin_ia32_phsubsw256 (v16hi,v16hi)
v32qi __builtin_ia32_pmaddubsw256 (v32qi,v32qi)
v16hi __builtin_ia32_pmaddwd256 (v16hi,v16hi)
v32qi __builtin_ia32_pmaxsb256 (v32qi,v32qi)
v16hi __builtin_ia32_pmaxsw256 (v16hi,v16hi)
v8si __builtin_ia32_pmaxsd256 (v8si,v8si)
v32qi __builtin_ia32_pmaxub256 (v32qi,v32qi)
v16hi __builtin_ia32_pmaxuw256 (v16hi,v16hi)
v8si __builtin_ia32_pmaxud256 (v8si,v8si)
v32qi __builtin_ia32_pminsb256 (v32qi,v32qi)
v16hi __builtin_ia32_pminsw256 (v16hi,v16hi)
v8si __builtin_ia32_pminsd256 (v8si,v8si)
v32qi __builtin_ia32_pminub256 (v32qi,v32qi)
v16hi __builtin_ia32_pminuw256 (v16hi,v16hi)
v8si __builtin_ia32_pminud256 (v8si,v8si)
int __builtin_ia32_pmovmskb256 (v32qi)
v16hi __builtin_ia32_pmovsxbw256 (v16qi)
v8si __builtin_ia32_pmovsxbd256 (v16qi)
v4di __builtin_ia32_pmovsxbq256 (v16qi)
v8si __builtin_ia32_pmovsxwd256 (v8hi)
v4di __builtin_ia32_pmovsxwq256 (v8hi)
v4di __builtin_ia32_pmovsxdq256 (v4si)
v16hi __builtin_ia32_pmovzxbw256 (v16qi)
v8si __builtin_ia32_pmovzxbd256 (v16qi)
v4di __builtin_ia32_pmovzxbq256 (v16qi)
v8si __builtin_ia32_pmovzxwd256 (v8hi)
v4di __builtin_ia32_pmovzxwq256 (v8hi)
v4di __builtin_ia32_pmovzxdq256 (v4si)
v4di __builtin_ia32_pmuldq256 (v8si,v8si)
v16hi __builtin_ia32_pmulhrsw256 (v16hi, v16hi)
v16hi __builtin_ia32_pmulhuw256 (v16hi,v16hi)
v16hi __builtin_ia32_pmulhw256 (v16hi,v16hi)
v16hi __builtin_ia32_pmullw256 (v16hi,v16hi)
v8si __builtin_ia32_pmulld256 (v8si,v8si)
v4di __builtin_ia32_pmuludq256 (v8si,v8si)
v4di __builtin_ia32_por256 (v4di,v4di)
v16hi __builtin_ia32_psadbw256 (v32qi,v32qi)
v32qi __builtin_ia32_pshufb256 (v32qi,v32qi)
v8si __builtin_ia32_pshufd256 (v8si,int)
v16hi __builtin_ia32_pshufhw256 (v16hi,int)
v16hi __builtin_ia32_pshuflw256 (v16hi,int)
v32qi __builtin_ia32_psignb256 (v32qi,v32qi)
v16hi __builtin_ia32_psignw256 (v16hi,v16hi)
v8si __builtin_ia32_psignd256 (v8si,v8si)
v4di __builtin_ia32_pslldqi256 (v4di,int)
v16hi __builtin_ia32_psllwi256 (16hi,int)
v8si __builtin_ia32_pslldi256 (v8si,int)
v4di __builtin_ia32_psllqi256 (v4di,int)
v16hi __builtin_ia32_psrawi256 (v16hi,int)
v16hi __builtin_ia32_psraw256 (v16hi,v8hi)
v8si __builtin_ia32_psradi256 (v8si,int)
v8si __builtin_ia32_psrad256 (v8si,v4si)
v4di __builtin_ia32_psrldqi256 (v4di, int)
v16hi __builtin_ia32_psrlwi256 (v16hi,int)
v16hi __builtin_ia32_psrlw256 (v16hi,v8hi)
v8si __builtin_ia32_psrldi256 (v8si,int)
v8si __builtin_ia32_psrld256 (v8si,v4si)
v4di __builtin_ia32_psrlqi256 (v4di,int)
v32qi __builtin_ia32_psubb256 (v32qi,v32qi)
v32hi __builtin_ia32_psubw256 (v16hi,v16hi)
v8si __builtin_ia32_psubd256 (v8si,v8si)
v4di __builtin_ia32_psubq256 (v4di,v4di)
v32qi __builtin_ia32_psubsb256 (v32qi,v32qi)
v16hi __builtin_ia32_psubsw256 (v16hi,v16hi)
v32qi __builtin_ia32_psubusb256 (v32qi,v32qi)
v16hi __builtin_ia32_psubusw256 (v16hi,v16hi)
v32qi __builtin_ia32_punpckhbw256 (v32qi,v32qi)
v16hi __builtin_ia32_punpckhwd256 (v16hi,v16hi)
v8si __builtin_ia32_punpckhdq256 (v8si,v8si)
v4di __builtin_ia32_punpckhqdq256 (v4di,v4di)
v32qi __builtin_ia32_punpcklbw256 (v32qi,v32qi)
v16hi __builtin_ia32_punpcklwd256 (v16hi,v16hi)
v8si __builtin_ia32_punpckldq256 (v8si,v8si)
v4di __builtin_ia32_punpcklqdq256 (v4di,v4di)
v4di __builtin_ia32_pxor256 (v4di,v4di)
v4di __builtin_ia32_movntdqa256 (pv4di)
v4sf __builtin_ia32_vbroadcastss_ps (v4sf)
v8sf __builtin_ia32_vbroadcastss_ps256 (v4sf)
v4df __builtin_ia32_vbroadcastsd_pd256 (v2df)
v4di __builtin_ia32_vbroadcastsi256 (v2di)
v4si __builtin_ia32_pblendd128 (v4si,v4si)
v8si __builtin_ia32_pblendd256 (v8si,v8si)
v32qi __builtin_ia32_pbroadcastb256 (v16qi)
v16hi __builtin_ia32_pbroadcastw256 (v8hi)
v8si __builtin_ia32_pbroadcastd256 (v4si)
v4di __builtin_ia32_pbroadcastq256 (v2di)
v16qi __builtin_ia32_pbroadcastb128 (v16qi)
v8hi __builtin_ia32_pbroadcastw128 (v8hi)
v4si __builtin_ia32_pbroadcastd128 (v4si)
v2di __builtin_ia32_pbroadcastq128 (v2di)
v8si __builtin_ia32_permvarsi256 (v8si,v8si)
v4df __builtin_ia32_permdf256 (v4df,int)
v8sf __builtin_ia32_permvarsf256 (v8sf,v8sf)
v4di __builtin_ia32_permdi256 (v4di,int)
v4di __builtin_ia32_permti256 (v4di,v4di,int)
v4di __builtin_ia32_extract128i256 (v4di,int)
v4di __builtin_ia32_insert128i256 (v4di,v2di,int)
v8si __builtin_ia32_maskloadd256 (pcv8si,v8si)
v4di __builtin_ia32_maskloadq256 (pcv4di,v4di)
__builtin_ia32_maskloadd (pcv4si,v4si)
__builtin_ia32_maskloadq (pcv2di,v2di)
__builtin_ia32_maskstored256 (pv8si,v8si,v8si)
__builtin_ia32_maskstoreq256 (pv4di,v4di,v4di)
__builtin_ia32_maskstored (pv4si,v4si,v4si)
__builtin_ia32_maskstoreq (pv2di,v2di,v2di)
__builtin_ia32_psllv8si (v8si,v8si)
__builtin_ia32_psllv4si (v4si,v4si)
__builtin_ia32_psllv4di (v4di,v4di)
__builtin_ia32_psllv2di (v2di,v2di)
__builtin_ia32_psrav8si (v8si,v8si)
__builtin_ia32_psrav4si (v4si,v4si)
__builtin_ia32_psrlv8si (v8si,v8si)
__builtin_ia32_psrlv4si (v4si,v4si)
__builtin_ia32_psrlv4di (v4di,v4di)
__builtin_ia32_psrlv2di (v2di,v2di)
__builtin_ia32_gathersiv2df (v2df, pcdouble,v4si,v2df,int)
__builtin_ia32_gathersiv4df (v4df, pcdouble,v4si,v4df,int)
__builtin_ia32_gatherdiv2df (v2df, pcdouble,v2di,v2df,int)
__builtin_ia32_gatherdiv4df (v4df, pcdouble,v4di,v4df,int)
__builtin_ia32_gathersiv4sf (v4sf, pcfloat,v4si,v4sf,int)
__builtin_ia32_gathersiv8sf (v8sf, pcfloat,v8si,v8sf,int)
__builtin_ia32_gatherdiv4sf (v4sf, pcfloat,v2di,v4sf,int)
__builtin_ia32_gatherdiv4sf256 (v4sf, pcfloat,v4di,v4sf,int)
__builtin_ia32_gathersiv2di (v2di, pcint64,v4si,v2di,int)
__builtin_ia32_gathersiv4di (v4di, pcint64,v4si,v4di,int)
__builtin_ia32_gatherdiv2di (v2di, pcint64,v2di,v2di,int)
__builtin_ia32_gatherdiv4di (v4di, pcint64,v4di,v4di,int)
__builtin_ia32_gathersiv4si (v4si, pcint,v4si,v4si,int)
__builtin_ia32_gathersiv8si (v8si, pcint,v8si,v8si,int)
__builtin_ia32_gatherdiv4si (v4si, pcint,v2di,v4si,int)
__builtin_ia32_gatherdiv4si256 (v4si, pcint,v4di,v4si,int)
__builtin_ia32_aesenc128 (v2di, v2di)
__builtin_ia32_aesenclast128 (v2di, v2di)
__builtin_ia32_aesdec128 (v2di, v2di)
__builtin_ia32_aesdeclast128 (v2di, v2di)
__builtin_ia32_aeskeygenassist128 (v2di, const int)
__builtin_ia32_aesimc128 (v2di)
v2di __builtin_ia32_pclmulqdq128 (v2di, v2di, const int)
unsigned int __builtin_ia32_rdfsbase32 (void)
unsigned long long __builtin_ia32_rdfsbase64 (void)
unsigned int __builtin_ia32_rdgsbase32 (void)
unsigned long long __builtin_ia32_rdgsbase64 (void)
unsigned int __builtin_ia32_rdrand16_step (unsigned short *)
unsigned int __builtin_ia32_rdrand32_step (unsigned int *)
unsigned int __builtin_ia32_rdrand64_step (unsigned long long *)
__builtin_ia32_movntsd (double *, v2df)
__builtin_ia32_movntss (float *, v4sf)
__builtin_ia32_extrq (v2di, v16qi)
__builtin_ia32_extrqi (v2di, const unsigned int, const unsigned int)
__builtin_ia32_insertq (v2di, v2di)
__builtin_ia32_insertqi (v2di, v2di, const unsigned int, const unsigned int)
v2df __builtin_ia32_vfrczpd (v2df)
v4sf __builtin_ia32_vfrczps (v4sf)
v2df __builtin_ia32_vfrczsd (v2df)
v4sf __builtin_ia32_vfrczss (v4sf)
v4df __builtin_ia32_vfrczpd256 (v4df)
v8sf __builtin_ia32_vfrczps256 (v8sf)
v2di __builtin_ia32_vpcmov (v2di, v2di, v2di)
v2di __builtin_ia32_vpcmov_v2di (v2di, v2di, v2di)
v4si __builtin_ia32_vpcmov_v4si (v4si, v4si, v4si)
v8hi __builtin_ia32_vpcmov_v8hi (v8hi, v8hi, v8hi)
v16qi __builtin_ia32_vpcmov_v16qi (v16qi, v16qi, v16qi)
v2df __builtin_ia32_vpcmov_v2df (v2df, v2df, v2df)
v4sf __builtin_ia32_vpcmov_v4sf (v4sf, v4sf, v4sf)
v4di __builtin_ia32_vpcmov_v4di256 (v4di, v4di, v4di)
v8si __builtin_ia32_vpcmov_v8si256 (v8si, v8si, v8si)
v16hi __builtin_ia32_vpcmov_v16hi256 (v16hi, v16hi, v16hi)
v32qi __builtin_ia32_vpcmov_v32qi256 (v32qi, v32qi, v32qi)
v4df __builtin_ia32_vpcmov_v4df256 (v4df, v4df, v4df)
v8sf __builtin_ia32_vpcmov_v8sf256 (v8sf, v8sf, v8sf)
v16qi __builtin_ia32_vpcomeqb (v16qi, v16qi)
v8hi __builtin_ia32_vpcomeqw (v8hi, v8hi)
v4si __builtin_ia32_vpcomeqd (v4si, v4si)
v2di __builtin_ia32_vpcomeqq (v2di, v2di)
v16qi __builtin_ia32_vpcomequb (v16qi, v16qi)
v4si __builtin_ia32_vpcomequd (v4si, v4si)
v2di __builtin_ia32_vpcomequq (v2di, v2di)
v8hi __builtin_ia32_vpcomequw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomeqw (v8hi, v8hi)
v16qi __builtin_ia32_vpcomfalseb (v16qi, v16qi)
v4si __builtin_ia32_vpcomfalsed (v4si, v4si)
v2di __builtin_ia32_vpcomfalseq (v2di, v2di)
v16qi __builtin_ia32_vpcomfalseub (v16qi, v16qi)
v4si __builtin_ia32_vpcomfalseud (v4si, v4si)
v2di __builtin_ia32_vpcomfalseuq (v2di, v2di)
v8hi __builtin_ia32_vpcomfalseuw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomfalsew (v8hi, v8hi)
v16qi __builtin_ia32_vpcomgeb (v16qi, v16qi)
v4si __builtin_ia32_vpcomged (v4si, v4si)
v2di __builtin_ia32_vpcomgeq (v2di, v2di)
v16qi __builtin_ia32_vpcomgeub (v16qi, v16qi)
v4si __builtin_ia32_vpcomgeud (v4si, v4si)
v2di __builtin_ia32_vpcomgeuq (v2di, v2di)
v8hi __builtin_ia32_vpcomgeuw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomgew (v8hi, v8hi)
v16qi __builtin_ia32_vpcomgtb (v16qi, v16qi)
v4si __builtin_ia32_vpcomgtd (v4si, v4si)
v2di __builtin_ia32_vpcomgtq (v2di, v2di)
v16qi __builtin_ia32_vpcomgtub (v16qi, v16qi)
v4si __builtin_ia32_vpcomgtud (v4si, v4si)
v2di __builtin_ia32_vpcomgtuq (v2di, v2di)
v8hi __builtin_ia32_vpcomgtuw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomgtw (v8hi, v8hi)
v16qi __builtin_ia32_vpcomleb (v16qi, v16qi)
v4si __builtin_ia32_vpcomled (v4si, v4si)
v2di __builtin_ia32_vpcomleq (v2di, v2di)
v16qi __builtin_ia32_vpcomleub (v16qi, v16qi)
v4si __builtin_ia32_vpcomleud (v4si, v4si)
v2di __builtin_ia32_vpcomleuq (v2di, v2di)
v8hi __builtin_ia32_vpcomleuw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomlew (v8hi, v8hi)
v16qi __builtin_ia32_vpcomltb (v16qi, v16qi)
v4si __builtin_ia32_vpcomltd (v4si, v4si)
v2di __builtin_ia32_vpcomltq (v2di, v2di)
v16qi __builtin_ia32_vpcomltub (v16qi, v16qi)
v4si __builtin_ia32_vpcomltud (v4si, v4si)
v2di __builtin_ia32_vpcomltuq (v2di, v2di)
v8hi __builtin_ia32_vpcomltuw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomltw (v8hi, v8hi)
v16qi __builtin_ia32_vpcomneb (v16qi, v16qi)
v4si __builtin_ia32_vpcomned (v4si, v4si)
v2di __builtin_ia32_vpcomneq (v2di, v2di)
v16qi __builtin_ia32_vpcomneub (v16qi, v16qi)
v4si __builtin_ia32_vpcomneud (v4si, v4si)
v2di __builtin_ia32_vpcomneuq (v2di, v2di)
v8hi __builtin_ia32_vpcomneuw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomnew (v8hi, v8hi)
v16qi __builtin_ia32_vpcomtrueb (v16qi, v16qi)
v4si __builtin_ia32_vpcomtrued (v4si, v4si)
v2di __builtin_ia32_vpcomtrueq (v2di, v2di)
v16qi __builtin_ia32_vpcomtrueub (v16qi, v16qi)
v4si __builtin_ia32_vpcomtrueud (v4si, v4si)
v2di __builtin_ia32_vpcomtrueuq (v2di, v2di)
v8hi __builtin_ia32_vpcomtrueuw (v8hi, v8hi)
v8hi __builtin_ia32_vpcomtruew (v8hi, v8hi)
v4si __builtin_ia32_vphaddbd (v16qi)
v2di __builtin_ia32_vphaddbq (v16qi)
v8hi __builtin_ia32_vphaddbw (v16qi)
v2di __builtin_ia32_vphadddq (v4si)
v4si __builtin_ia32_vphaddubd (v16qi)
v2di __builtin_ia32_vphaddubq (v16qi)
v8hi __builtin_ia32_vphaddubw (v16qi)
v2di __builtin_ia32_vphaddudq (v4si)
v4si __builtin_ia32_vphadduwd (v8hi)
v2di __builtin_ia32_vphadduwq (v8hi)
v4si __builtin_ia32_vphaddwd (v8hi)
v2di __builtin_ia32_vphaddwq (v8hi)
v8hi __builtin_ia32_vphsubbw (v16qi)
v2di __builtin_ia32_vphsubdq (v4si)
v4si __builtin_ia32_vphsubwd (v8hi)
v4si __builtin_ia32_vpmacsdd (v4si, v4si, v4si)
v2di __builtin_ia32_vpmacsdqh (v4si, v4si, v2di)
v2di __builtin_ia32_vpmacsdql (v4si, v4si, v2di)
v4si __builtin_ia32_vpmacssdd (v4si, v4si, v4si)
v2di __builtin_ia32_vpmacssdqh (v4si, v4si, v2di)
v2di __builtin_ia32_vpmacssdql (v4si, v4si, v2di)
v4si __builtin_ia32_vpmacsswd (v8hi, v8hi, v4si)
v8hi __builtin_ia32_vpmacssww (v8hi, v8hi, v8hi)
v4si __builtin_ia32_vpmacswd (v8hi, v8hi, v4si)
v8hi __builtin_ia32_vpmacsww (v8hi, v8hi, v8hi)
v4si __builtin_ia32_vpmadcsswd (v8hi, v8hi, v4si)
v4si __builtin_ia32_vpmadcswd (v8hi, v8hi, v4si)
v16qi __builtin_ia32_vpperm (v16qi, v16qi, v16qi)
v16qi __builtin_ia32_vprotb (v16qi, v16qi)
v4si __builtin_ia32_vprotd (v4si, v4si)
v2di __builtin_ia32_vprotq (v2di, v2di)
v8hi __builtin_ia32_vprotw (v8hi, v8hi)
v16qi __builtin_ia32_vpshab (v16qi, v16qi)
v4si __builtin_ia32_vpshad (v4si, v4si)
v2di __builtin_ia32_vpshaq (v2di, v2di)
v8hi __builtin_ia32_vpshaw (v8hi, v8hi)
v16qi __builtin_ia32_vpshlb (v16qi, v16qi)
v4si __builtin_ia32_vpshld (v4si, v4si)
v2di __builtin_ia32_vpshlq (v2di, v2di)
v8hi __builtin_ia32_vpshlw (v8hi, v8hi)
__builtin_ia32_vfmaddpd (v2df, v2df, v2df)
__builtin_ia32_vfmaddps (v4sf, v4sf, v4sf)
__builtin_ia32_vfmaddsd (v2df, v2df, v2df)
__builtin_ia32_vfmaddss (v4sf, v4sf, v4sf)
__builtin_ia32_vfmsubpd (v2df, v2df, v2df)
__builtin_ia32_vfmsubps (v4sf, v4sf, v4sf)
__builtin_ia32_vfmsubsd (v2df, v2df, v2df)
__builtin_ia32_vfmsubss (v4sf, v4sf, v4sf)
__builtin_ia32_vfnmaddpd (v2df, v2df, v2df)
__builtin_ia32_vfnmaddps (v4sf, v4sf, v4sf)
__builtin_ia32_vfnmaddsd (v2df, v2df, v2df)
__builtin_ia32_vfnmaddss (v4sf, v4sf, v4sf)
__builtin_ia32_vfnmsubpd (v2df, v2df, v2df)
__builtin_ia32_vfnmsubps (v4sf, v4sf, v4sf)
__builtin_ia32_vfnmsubsd (v2df, v2df, v2df)
__builtin_ia32_vfnmsubss (v4sf, v4sf, v4sf)
__builtin_ia32_vfmaddsubpd (v2df, v2df, v2df)
__builtin_ia32_vfmaddsubps (v4sf, v4sf, v4sf)
__builtin_ia32_vfmsubaddpd (v2df, v2df, v2df)
__builtin_ia32_vfmsubaddps (v4sf, v4sf, v4sf)
__builtin_ia32_vfmaddpd256 (v4df, v4df, v4df)
__builtin_ia32_vfmaddps256 (v8sf, v8sf, v8sf)
__builtin_ia32_vfmsubpd256 (v4df, v4df, v4df)
__builtin_ia32_vfmsubps256 (v8sf, v8sf, v8sf)
__builtin_ia32_vfnmaddpd256 (v4df, v4df, v4df)
__builtin_ia32_vfnmaddps256 (v8sf, v8sf, v8sf)
__builtin_ia32_vfnmsubpd256 (v4df, v4df, v4df)
__builtin_ia32_vfnmsubps256 (v8sf, v8sf, v8sf)
__builtin_ia32_vfmaddsubpd256 (v4df, v4df, v4df)
__builtin_ia32_vfmaddsubps256 (v8sf, v8sf, v8sf)
__builtin_ia32_vfmsubaddpd256 (v4df, v4df, v4df)
v8sf __builtin_ia32_vfmsubaddps256 (v8sf, v8sf, v8sf)
void __builtin_ia32_llwpcb16 (void *);
void __builtin_ia32_llwpcb32 (void *);
void __builtin_ia32_llwpcb64 (void *);
void * __builtin_ia32_llwpcb16 (void);
void * __builtin_ia32_llwpcb32 (void);
void * __builtin_ia32_llwpcb64 (void);
void __builtin_ia32_lwpval16 (unsigned short, unsigned int, unsigned short)
void __builtin_ia32_lwpval32 (unsigned int, unsigned int, unsigned int)
void __builtin_ia32_lwpval64 (unsigned __int64, unsigned int, unsigned int)
unsigned char __builtin_ia32_lwpins16 (unsigned short, unsigned int, unsigned short)
unsigned char __builtin_ia32_lwpins32 (unsigned int, unsigned int, unsigned int)
unsigned char __builtin_ia32_lwpins64 (unsigned __int64, unsigned int, unsigned int)
unsigned long long __builtin_ia32_bextr_u64 (unsigned long long, unsigned long long);
unsigned long long __builtin_ia32_lzcnt_u64 (unsigned long long);
__builtin_ia32_fxsave (void *)
__builtin_ia32_fxrstor (void *)
__builtin_ia32_fxsave64 (void *)
__builtin_ia32_fxrstor64 (void *)
__builtin_ia32_xsave (void *, long long)
__builtin_ia32_xrstor (void *, long long)
__builtin_ia32_xsave64 (void *, long long)
__builtin_ia32_xrstor64 (void *, long long)
void __builtin_ia32_xsaveopt (void *, long long)
void __builtin_ia32_xsaveopt64 (void *, long long)
unsigned int __builtin_ia32_bextri_u32 (unsigned int, const unsigned int);
unsigned long long __builtin_ia32_bextri_u64 (unsigned long long, const unsigned long long);
__builtin_ia32_femms (void)
__builtin_ia32_pavgusb (v8qi, v8qi)
__builtin_ia32_pf2id (v2sf)
__builtin_ia32_pfacc (v2sf, v2sf)
__builtin_ia32_pfadd (v2sf, v2sf)
__builtin_ia32_pfcmpeq (v2sf, v2sf)
__builtin_ia32_pfcmpge (v2sf, v2sf)
__builtin_ia32_pfcmpgt (v2sf, v2sf)
__builtin_ia32_pfmax (v2sf, v2sf)
__builtin_ia32_pfmin (v2sf, v2sf)
__builtin_ia32_pfmul (v2sf, v2sf)
__builtin_ia32_pfrcp (v2sf)
__builtin_ia32_pfrcpit1 (v2sf, v2sf)
__builtin_ia32_pfrcpit2 (v2sf, v2sf)
__builtin_ia32_pfrsqrt (v2sf)
__builtin_ia32_pfsub (v2sf, v2sf)
__builtin_ia32_pfsubr (v2sf, v2sf)
__builtin_ia32_pi2fd (v2si)
__builtin_ia32_pmulhrw (v4hi, v4hi)
__builtin_ia32_pf2iw (v2sf)
__builtin_ia32_pfnacc (v2sf, v2sf)
__builtin_ia32_pfpnacc (v2sf, v2sf)
__builtin_ia32_pi2fw (v2si)
__builtin_ia32_pswapdsf (v2sf)
__builtin_ia32_pswapdsi (v2si)
int __builtin_ia32_xbegin ()
void __builtin_ia32_xend ()
void __builtin_ia32_xabort (status)
int __builtin_ia32_xtest ()
void __builtin_ia32_monitorx (void *, unsigned int, unsigned int)
void __builtin_ia32_mwaitx (unsigned int, unsigned int, unsigned int)
void __builtin_i32_clzero (void *)
void __builtin_ia32_wrpkru (unsigned int)
unsigned int __builtin_ia32_rdpkru ()
